export default [
	{
		name: 'Afghanistan',
		subregions: [
			{ name: 'Badakhshan Province' },
			{ name: 'Badghis' },
			{ name: 'Baghlan Province' },
			{ name: 'Balkh Province' },
			{ name: 'Bamyan' },
			{ name: 'Daykundi' },
			{ name: 'Farah Province' },
			{ name: 'Faryab' },
			{ name: 'Ghazni Province' },
			{ name: 'Ghor' },
			{ name: 'Helmand' },
			{ name: 'Jowzjan Province' },
			{ name: 'Kabul Province' },
			{ name: 'Kandahar' },
			{ name: 'Kapisa Province' },
			{ name: 'Khost Province' },
			{ name: 'Kunar Province' },
			{ name: 'Kunduz Province' },
			{ name: 'Laghman Province' },
			{ name: 'Logar Province' },
			{ name: 'Maidan Wardak' },
			{ name: 'Nangarhar Province' },
			{ name: 'Nimruz Province' },
			{ name: 'Nuristan Province' },
			{ name: 'Paktia Province' },
			{ name: 'Paktika Province' },
			{ name: 'Panjshir Province' },
			{ name: 'Parwan Province' },
			{ name: 'Samangan' },
			{ name: 'Sar-e Pol Province' },
			{ name: 'Takhar Province' },
			{ name: 'Urōzgān' },
			{ name: 'Zabul Province' },
		],
	},
	{
		name: 'Albania',
		subregions: [{ name: 'Central Albania' }, { name: 'Northern Albania' }, { name: 'Southern Albania' }],
	},
	{
		name: 'Algeria',
		subregions: [
			{ name: 'Adrar' },
			{ name: 'Aïn Defla' },
			{ name: 'Aïn Témouchent' },
			{ name: 'Algiers' },
			{ name: 'Annaba' },
			{ name: 'Bashar' },
			{ name: 'Batna' },
			{ name: 'Bejaia' },
			{ name: 'Beni Abbes' },
			{ name: 'Biskra' },
			{ name: 'Blida' },
			{ name: 'Bordj Badji Mokhtar' },
			{ name: 'Bordj Bou Arreridj' },
			{ name: 'Bouira' },
			{ name: 'Boumerdès' },
			{ name: 'Chlef' },
			{ name: 'Constantine' },
			{ name: 'Djanet' },
			{ name: 'Djelfa' },
			{ name: 'El Bayadh' },
			{ name: "El M'Ghair" },
			{ name: 'El Menia' },
			{ name: 'El Oued' },
			{ name: 'El Tarf' },
			{ name: 'Ghardaia' },
			{ name: 'Guelma' },
			{ name: 'Illizi' },
			{ name: 'In Guezzam' },
			{ name: 'In Salah' },
			{ name: 'Jijel' },
			{ name: 'Khenchela' },
			{ name: 'Laghouat' },
			{ name: "M'Sila" },
			{ name: 'Mascara' },
			{ name: 'Médéa' },
			{ name: 'Mila' },
			{ name: 'Mostaganem' },
			{ name: 'Naâma' },
			{ name: 'Oran' },
			{ name: 'Ouargla' },
			{ name: 'Ouled Djellal' },
			{ name: 'Oum El Bouaghi' },
			{ name: 'Relizane' },
			{ name: 'Saïda' },
			{ name: 'Setif' },
			{ name: 'Sidi Bel Abbès' },
			{ name: 'Skikda' },
			{ name: 'Souk Ahras' },
			{ name: 'Tamanrasset' },
			{ name: 'Tébessa' },
			{ name: 'Tiaret' },
			{ name: 'Tilimsen' },
			{ name: 'Timimoune' },
			{ name: 'Tinduf' },
			{ name: 'Tipaza' },
			{ name: 'Tissemsilt' },
			{ name: 'Tizi Ouzou' },
			{ name: 'Touggourt' },
		],
	},
	{
		name: 'Angola',
		subregions: [
			{ name: 'Bengo' },
			{ name: 'Benguela' },
			{ name: 'Bié' },
			{ name: 'Cabinda' },
			{ name: 'Cuando Cubango' },
			{ name: 'Cuanza Sul' },
			{ name: 'Cunene' },
			{ name: 'Huambo' },
			{ name: 'Huíla' },
			{ name: 'Luanda Province' },
			{ name: 'Lunda Norte' },
			{ name: 'Lunda Sul' },
			{ name: 'Malanje' },
			{ name: 'Moxico' },
			{ name: 'Namibe' },
			{ name: 'Uíge' },
			{ name: 'Zaire' },
		],
	},
	{ name: 'Antigua and Barbuda', subregions: [{ name: 'Barbuda' }, { name: 'Redonda' }] },
	{
		name: 'Argentina',
		subregions: [
			{ name: 'Autonomous City of Buenos Aires' },
			{ name: 'Buenos Aires' },
			{ name: 'Catamarca' },
			{ name: 'Chaco' },
			{ name: 'Chubut' },
			{ name: 'Córdoba' },
			{ name: 'Formosa' },
			{ name: 'Jujuy' },
			{ name: 'La Pampa' },
			{ name: 'La Rioja' },
			{ name: 'Mendoza' },
			{ name: 'Misiones' },
			{ name: 'Neuquén Province' },
			{ name: 'Río Negro Province' },
			{ name: 'Salta' },
			{ name: 'San Juan' },
			{ name: 'San Luis' },
			{ name: 'Santa Cruz Province, Argentina' },
			{ name: 'Santa Fe' },
			{ name: 'Santiago del Estero' },
			{ name: 'Tierra del Fuego Province' },
			{ name: 'Tucumán' },
		],
	},
	{
		name: 'Armenia',
		subregions: [
			{ name: 'Aragatsotn Province' },
			{ name: 'Ararat Province' },
			{ name: 'Armavir Province' },
			{ name: 'Gegharkunik Province' },
			{ name: 'Kotayk Province' },
			{ name: 'Lori Province' },
			{ name: 'Shirak Province' },
			{ name: 'Syunik Province' },
			{ name: 'Tavush Province' },
			{ name: 'Vayots Dzor Province' },
			{ name: 'Yerevan' },
		],
	},
	{
		name: 'Australia',
		subregions: [
			{ name: 'Ashmore and Cartier Islands' },
			{ name: 'Australian Capital Territory' },
			{ name: 'Christmas Island' },
			{ name: 'Cocos (Keeling) Islands' },
			{ name: 'Coral Sea Islands' },
			{ name: 'Heard Island and McDonald Islands' },
			{ name: 'Jervis Bay Territory' },
			{ name: 'New South Wales' },
			{ name: 'Norfolk Island' },
			{ name: 'Northern Territory' },
			{ name: 'Queensland' },
			{ name: 'South Australia' },
			{ name: 'Tasmania' },
			{ name: 'Victoria' },
			{ name: 'Western Australia' },
		],
	},
	{
		name: 'Austria',
		subregions: [
			{ name: 'Burgenland' },
			{ name: 'Carinthia' },
			{ name: 'Lower Austria' },
			{ name: 'Salzburg' },
			{ name: 'Styria' },
			{ name: 'Tyrol' },
			{ name: 'Upper Austria' },
			{ name: 'Vienna' },
			{ name: 'Vorarlberg' },
		],
	},
	{
		name: 'Azerbaijan',
		subregions: [
			{ name: 'Absheron' },
			{ name: 'Aran' },
			{ name: 'Askeran Region' },
			{ name: 'Ganja-Qazakh' },
			{ name: 'Kalbajar-Lachin' },
			{ name: 'Lankaran' },
			{ name: 'Martakert Region' },
			{ name: 'Martuni Province' },
			{ name: 'Mountainous Shirvan' },
			{ name: 'Quba-Khachmaz' },
			{ name: 'Sheki-Zaqatala' },
			{ name: 'Shushi Region' },
			{ name: 'Stepanakert' },
			{ name: 'Upper Karabakh' },
		],
	},
	{
		name: 'Bahrain',
		subregions: [
			{ name: 'Capital Governorate' },
			{ name: 'Muharraq Governorate' },
			{ name: 'Northern Governorate' },
			{ name: 'Southern Governorate' },
		],
	},
	{
		name: 'Bangladesh',
		subregions: [
			{ name: 'Barishal Division' },
			{ name: 'Chattogram Division' },
			{ name: 'Dhaka Division' },
			{ name: 'Khulna Division' },
			{ name: 'Kishoreganj District' },
			{ name: 'Mymensingh Division' },
			{ name: 'Rajshahi Division' },
			{ name: 'Rangpur Division' },
			{ name: 'Sylhet Division' },
		],
	},
	{
		name: 'Belarus',
		subregions: [
			{ name: 'Brest Region' },
			{ name: 'Homyel Region' },
			{ name: 'Hrodna Region' },
			{ name: 'Mahilyow Region' },
			{ name: 'Minsk' },
			{ name: 'Minsk Region' },
			{ name: 'Vitsebsk Region' },
		],
	},
	{ name: 'Belgium', subregions: [{ name: 'Brussels-Capital' }, { name: 'Flanders' }, { name: 'Wallonia' }] },
	{
		name: 'Belize',
		subregions: [
			{ name: 'Belize District' },
			{ name: 'Cayo' },
			{ name: 'Corozal' },
			{ name: 'Orange Walk' },
			{ name: 'Stann Creek' },
			{ name: 'Toledo' },
		],
	},
	{
		name: 'Benin',
		subregions: [
			{ name: 'Alibori' },
			{ name: 'Atakora' },
			{ name: 'Atlantique' },
			{ name: 'Borgou' },
			{ name: 'Collines' },
			{ name: 'Donga' },
			{ name: 'Kouffo' },
			{ name: 'Littoral' },
			{ name: 'Mono' },
			{ name: 'Ouémé' },
			{ name: 'Plateau' },
			{ name: 'Zou' },
		],
	},
	{
		name: 'Bhutan',
		subregions: [
			{ name: 'Bumthang District' },
			{ name: 'Chukha District' },
			{ name: 'Dagana District' },
			{ name: 'Gasa District' },
			{ name: 'Haa District' },
			{ name: 'Lhuntse District' },
			{ name: 'Merag-Sagteng' },
			{ name: 'Mongar District' },
			{ name: 'Paro District' },
			{ name: 'Pemagatshel District' },
			{ name: 'Punakha District' },
			{ name: 'Samdrup Jongkhar District' },
			{ name: 'Samtse District' },
			{ name: 'Sarpang District' },
			{ name: 'Thimphu District' },
			{ name: 'Trashigang District' },
			{ name: 'Trongsa District' },
			{ name: 'Tsirang District' },
			{ name: 'Wangdue Phodrang District' },
			{ name: 'Zhemgang District' },
		],
	},
	{
		name: 'Bolivia',
		subregions: [
			{ name: 'Chuquisaca' },
			{ name: 'Cochabamba' },
			{ name: 'El Beni' },
			{ name: 'La Paz' },
			{ name: 'Oruro' },
			{ name: 'Pando' },
			{ name: 'Potosí' },
			{ name: 'Santa Cruz' },
			{ name: 'Tarija' },
		],
	},
	{
		name: 'Bosnia and Herzegovina',
		subregions: [
			{ name: 'Brčko District' },
			{ name: 'Federation of Bosnia and Herzegovina' },
			{ name: 'Republika Srpska' },
		],
	},
	{
		name: 'Botswana',
		subregions: [
			{ name: 'Central District' },
			{ name: 'Chobe District' },
			{ name: 'Ghanzi District' },
			{ name: 'Kgalagadi District' },
			{ name: 'Kgatleng District' },
			{ name: 'Kweneng District' },
			{ name: 'North-East District' },
			{ name: 'North-West District' },
			{ name: 'South-East District' },
			{ name: 'Southern District' },
		],
	},
	{
		name: 'Brazil',
		subregions: [
			{ name: 'Acre' },
			{ name: 'Alagoas' },
			{ name: 'Amapá' },
			{ name: 'Amazonas' },
			{ name: 'Bahia' },
			{ name: 'Ceará' },
			{ name: 'Espírito Santo' },
			{ name: 'Federal District' },
			{ name: 'Goiás' },
			{ name: 'Maranhão' },
			{ name: 'Mato Grosso' },
			{ name: 'Mato Grosso do Sul' },
			{ name: 'Minas Gerais' },
			{ name: 'Pará' },
			{ name: 'Paraíba' },
			{ name: 'Paraná' },
			{ name: 'Pernambuco' },
			{ name: 'Piauí' },
			{ name: 'Rio de Janeiro' },
			{ name: 'Rio Grande do Norte' },
			{ name: 'Rio Grande do Sul' },
			{ name: 'Rondônia' },
			{ name: 'Roraima' },
			{ name: 'Santa Catarina' },
			{ name: 'São Paulo' },
			{ name: 'Sergipe' },
			{ name: 'Tocantins' },
		],
	},
	{
		name: 'Brunei',
		subregions: [
			{ name: 'Belait District' },
			{ name: 'Brunei-Muara District' },
			{ name: 'Temburong District' },
			{ name: 'Tutong District' },
		],
	},
	{
		name: 'Bulgaria',
		subregions: [
			{ name: 'Blagoevgrad' },
			{ name: 'Burgas' },
			{ name: 'Dobrich' },
			{ name: 'Gabrovo' },
			{ name: 'Haskovo' },
			{ name: 'Kardzhali' },
			{ name: 'Kyustendil' },
			{ name: 'Lovech' },
			{ name: 'Montana' },
			{ name: 'Pazardzhik' },
			{ name: 'Pernik' },
			{ name: 'Pleven' },
			{ name: 'Plovdiv' },
			{ name: 'Razgrad' },
			{ name: 'Ruse' },
			{ name: 'Shumen' },
			{ name: 'Silistra' },
			{ name: 'Sliven' },
			{ name: 'Smolyan' },
			{ name: 'Sofia' },
			{ name: 'Sofia-City' },
			{ name: 'Stara Zagora' },
			{ name: 'Targovishte' },
			{ name: 'Varna' },
			{ name: 'Veliko Tarnovo' },
			{ name: 'Vidin' },
			{ name: 'Vratsa' },
			{ name: 'Yambol' },
		],
	},
	{
		name: 'Burkina Faso',
		subregions: [
			{ name: 'Boucle du Mouhoun' },
			{ name: 'Central-East' },
			{ name: 'Central-North' },
			{ name: 'Central-Plateau' },
			{ name: 'Central-South' },
			{ name: 'Central-West' },
			{ name: 'Centre' },
			{ name: 'East' },
			{ name: 'North' },
			{ name: 'Sahel' },
			{ name: 'Southwest' },
			{ name: 'Upper-Basins' },
			{ name: 'Waterfalls' },
		],
	},
	{
		name: 'Burundi',
		subregions: [
			{ name: 'Bubanza' },
			{ name: 'Bujumbura Mairie' },
			{ name: 'Bujumbura Rural' },
			{ name: 'Bururi' },
			{ name: 'Cankuzo' },
			{ name: 'Cibitoke' },
			{ name: 'Gitega' },
			{ name: 'Karuzi' },
			{ name: 'Kayanza' },
			{ name: 'Kirundo' },
			{ name: 'Makamba' },
			{ name: 'Muramvya' },
			{ name: 'Muyinga' },
			{ name: 'Mwaro' },
			{ name: 'Ngozi' },
			{ name: 'Rumonge' },
			{ name: 'Rutana' },
			{ name: 'Ruyigi' },
		],
	},
	{
		name: 'Cambodia',
		subregions: [
			{ name: 'Bantey Meanchey' },
			{ name: 'Battambang' },
			{ name: 'Kampong Cham' },
			{ name: 'Kampong Chhnang' },
			{ name: 'Kampong Speu' },
			{ name: 'Kampong Thom' },
			{ name: 'Kampot' },
			{ name: 'Kandal' },
			{ name: 'Kep' },
			{ name: 'Khaet Preah Sihanouk' },
			{ name: 'Koh Kong' },
			{ name: 'Kratie' },
			{ name: 'Mondulkiri' },
			{ name: 'Oddar Meanchey' },
			{ name: 'Pailin' },
			{ name: 'Phnom Penh' },
			{ name: 'Preah Vihear' },
			{ name: 'Prey Veng' },
			{ name: 'Pursat' },
			{ name: 'Ratanakiri' },
			{ name: 'Siem Reap' },
			{ name: 'Stung Treng' },
			{ name: 'Svay Rieng' },
			{ name: 'Takeo' },
			{ name: 'Tbong Khmum' },
		],
	},
	{
		name: 'Cameroon',
		subregions: [
			{ name: 'Adamawa' },
			{ name: 'Centre' },
			{ name: 'East' },
			{ name: 'Far-North' },
			{ name: 'Littoral' },
			{ name: 'North' },
			{ name: 'Northwest' },
			{ name: 'South' },
			{ name: 'Southwest' },
			{ name: 'West' },
		],
	},
	{
		name: 'Canada',
		subregions: [
			{ name: 'Alberta' },
			{ name: 'British Columbia' },
			{ name: 'Manitoba' },
			{ name: 'New Brunswick' },
			{ name: 'Newfoundland and Labrador' },
			{ name: 'Northwest Territories' },
			{ name: 'Nova Scotia' },
			{ name: 'NU' },
			{ name: 'Nunavut' },
			{ name: 'Ontario' },
			{ name: 'Prince Edward Island' },
			{ name: 'Quebec' },
			{ name: 'Saskatchewan' },
			{ name: 'Yukon' },
		],
	},
	{
		name: 'Central African Republic',
		subregions: [
			{ name: 'Bamingui-Bangoran' },
			{ name: 'Bangui' },
			{ name: 'Basse-Kotto' },
			{ name: 'Haut-Mbomou' },
			{ name: 'Haute-Kotto' },
			{ name: 'Kémo' },
			{ name: 'Lobaye' },
			{ name: 'Mambéré-Kadéï' },
			{ name: 'Mbomou' },
			{ name: 'Nana-Grébizi' },
			{ name: 'Nana-Mambéré' },
			{ name: "Ombella M'Poko" },
			{ name: 'Ouaka' },
			{ name: 'Ouham' },
			{ name: 'Ouham-Pendé' },
			{ name: 'Sangha-Mbaéré' },
			{ name: 'Vakaga' },
		],
	},
	{
		name: 'Chad',
		subregions: [
			{ name: 'Bahr el Gazel' },
			{ name: 'Batha' },
			{ name: 'Borkou' },
			{ name: 'Chari-Baguirmi' },
			{ name: 'East Ennedi' },
			{ name: 'Ennedi-Ouest' },
			{ name: 'Guéra' },
			{ name: 'Hadjer-Lamis' },
			{ name: 'Kanem' },
			{ name: 'Lac' },
			{ name: 'Logone Occidental' },
			{ name: 'Logone Oriental' },
			{ name: 'Mandoul' },
			{ name: 'Mayo-Kebbi Est' },
			{ name: 'Mayo-Kebbi Ouest' },
			{ name: 'Moyen-Chari' },
			{ name: "N'Djamena" },
			{ name: 'Ouaddaï' },
			{ name: 'Salamat' },
			{ name: 'Sila' },
			{ name: 'Tandjilé' },
			{ name: 'Tibesti' },
			{ name: 'Wadi Fira' },
		],
	},
	{
		name: 'Chile',
		subregions: [
			{ name: 'Región Aysén del General Carlos Ibáñez del Campo' },
			{ name: 'Región de Antofagasta' },
			{ name: 'Región de Arica y Parinacota' },
			{ name: 'Región de Atacama' },
			{ name: 'Región de Coquimbo' },
			{ name: 'Región de la Araucanía' },
			{ name: 'Región de Los Lagos' },
			{ name: 'Región de Los Ríos' },
			{ name: 'Región de Ñuble' },
			{ name: 'Región de Tarapacá' },
			{ name: 'Región de Valparaíso' },
			{ name: 'Región del Biobío' },
			{ name: "Región del Libertador General Bernardo O'Higgins" },
			{ name: 'Región del Maule' },
			{ name: 'Región Metropolitana de Santiago' },
			{ name: 'Region of Magallanes and Chilean Antarctica' },
		],
	},
	{
		name: 'China',
		subregions: [
			{ name: 'Anhui' },
			{ name: 'Beijing' },
			{ name: 'Chongqing' },
			{ name: 'Fujian Province' },
			{ name: 'Gansu' },
			{ name: 'Guangdong Province' },
			{ name: 'Guangxi' },
			{ name: 'Guizhou' },
			{ name: 'Hainan Province' },
			{ name: 'Hebei' },
			{ name: 'Heilongjiang' },
			{ name: 'Henan' },
			{ name: 'Hubei' },
			{ name: 'Hunan' },
			{ name: 'Inner Mongolia' },
			{ name: 'Jiangsu' },
			{ name: 'Jiangxi' },
			{ name: 'Jilin' },
			{ name: 'Liaoning' },
			{ name: 'Ningxia' },
			{ name: 'Qinghai' },
			{ name: 'Shaanxi' },
			{ name: 'Shandong' },
			{ name: 'Shanxi' },
			{ name: 'Sichuan' },
			{ name: 'Tianjin' },
			{ name: 'Tibet' },
			{ name: 'Xinjiang' },
			{ name: 'Yunnan' },
			{ name: 'Zhejiang' },
		],
	},
	{
		name: 'Colombia',
		subregions: [
			{ name: 'Amazonas' },
			{ name: 'Antioquia' },
			{ name: 'Arauca' },
			{ name: 'Archipiélago de San Andrés, Providencia y Santa Catalina' },
			{ name: 'Atlántico' },
			{ name: 'Bolívar' },
			{ name: 'Boyacá' },
			{ name: 'Caldas' },
			{ name: 'Caquetá' },
			{ name: 'Casanare' },
			{ name: 'Cauca' },
			{ name: 'Cesar' },
			{ name: 'Chocó' },
			{ name: 'Córdoba' },
			{ name: 'Cundinamarca' },
			{ name: 'Guainía' },
			{ name: 'Guaviare' },
			{ name: 'Huila' },
			{ name: 'La Guajira' },
			{ name: 'Magdalena' },
			{ name: 'Meta' },
			{ name: 'Nariño' },
			{ name: 'Norte de Santander' },
			{ name: 'Putumayo' },
			{ name: 'Quindío' },
			{ name: 'Risaralda' },
			{ name: 'Santander' },
			{ name: 'Sucre' },
			{ name: 'Tolima' },
			{ name: 'Valle del Cauca' },
			{ name: 'Vaupés' },
			{ name: 'Vichada' },
		],
	},
	{ name: 'Comoros', subregions: [{ name: 'Anjouan' }, { name: 'Grande Comore' }, { name: 'Moheli' }] },
	{
		name: 'Congo-Brazzaville',
		subregions: [
			{ name: 'Bouenza' },
			{ name: 'Brazzaville' },
			{ name: 'Cuvette' },
			{ name: 'Cuvette-Ouest' },
			{ name: 'Kouilou' },
			{ name: 'Lékoumou' },
			{ name: 'Likouala' },
			{ name: 'Niari' },
			{ name: 'Plateaux' },
			{ name: 'Pointe-Noire' },
			{ name: 'Pool' },
			{ name: 'Sangha' },
		],
	},
	{ name: 'Cook Islands', subregions: [{ name: 'Mauke' }, { name: 'Rarotonga' }] },
	{
		name: 'Costa Rica',
		subregions: [
			{ name: 'Alajuela Province' },
			{ name: 'Cartago Province' },
			{ name: 'Heredia Province' },
			{ name: 'Limón Province' },
			{ name: 'Provincia Guanacaste' },
			{ name: 'Provincia Puntarenas' },
			{ name: 'San Jose Province' },
		],
	},
	{
		name: 'Cuba',
		subregions: [
			{ name: 'Artemisa' },
			{ name: 'Camagüey' },
			{ name: 'Ciego de Avila' },
			{ name: 'Cienfuegos' },
			{ name: 'Granma' },
			{ name: 'Guantánamo' },
			{ name: 'Havana' },
			{ name: 'Holguín' },
			{ name: 'Isle of Youth' },
			{ name: 'Las Tunas' },
			{ name: 'Matanzas' },
			{ name: 'Mayabeque' },
			{ name: 'Pinar del Rio' },
			{ name: 'Sancti Spiritus' },
			{ name: 'Santiago de Cuba' },
			{ name: 'Villa Clara' },
		],
	},
	{
		name: 'Czechia',
		subregions: [
			{ name: 'Central Bohemia' },
			{ name: 'Central Moravia' },
			{ name: 'Moravia-Silesia' },
			{ name: 'Northeast' },
			{ name: 'Northwest' },
			{ name: 'Prague' },
			{ name: 'Southeast' },
			{ name: 'Southwest' },
		],
	},
	{
		name: "Côte d'Ivoire",
		subregions: [
			{ name: 'Abidjan' },
			{ name: 'Bas-Sassandra' },
			{ name: 'Comoé' },
			{ name: 'Denguélé' },
			{ name: 'Gôh-Djiboua' },
			{ name: 'Lacs' },
			{ name: 'Lagunes' },
			{ name: 'Montagnes' },
			{ name: 'Sassandra-Marahoué' },
			{ name: 'Savanes' },
			{ name: 'Vallée du Bandama' },
			{ name: 'Woroba' },
			{ name: 'Yamoussoukro' },
			{ name: 'Zanzan' },
		],
	},
	{
		name: 'Democratic Republic of the Congo',
		subregions: [
			{ name: 'Central Kasai' },
			{ name: 'Équateur' },
			{ name: 'Haut-Katanga' },
			{ name: 'Haut-Lomami' },
			{ name: 'Ituri' },
			{ name: 'Kasai' },
			{ name: 'Kasai-Oriental' },
			{ name: 'Kinshasa' },
			{ name: 'Kongo-Central' },
			{ name: 'Kwango' },
			{ name: 'Kwilu' },
			{ name: 'Lomami' },
			{ name: 'Lower Uele' },
			{ name: 'Lualaba' },
			{ name: 'Mai-Ndombe' },
			{ name: 'Maniema' },
			{ name: 'Mongala' },
			{ name: 'Nord-Ubangi' },
			{ name: 'North Kivu' },
			{ name: 'Sankuru' },
			{ name: 'South Kivu' },
			{ name: 'Sud-Ubangi' },
			{ name: 'Tanganyika' },
			{ name: 'Tshopo' },
			{ name: 'Tshuapa' },
			{ name: 'Upper Uele' },
		],
	},
	{
		name: 'Denmark',
		subregions: [
			{ name: 'Capital Region of Denmark' },
			{ name: 'Central Denmark Region' },
			{ name: 'North Denmark Region' },
			{ name: 'Region of Southern Denmark' },
			{ name: 'Region Zealand' },
		],
	},
	{
		name: 'Djibouti',
		subregions: [
			{ name: 'Ali Sabieh' },
			{ name: 'Arta' },
			{ name: 'Dikhil' },
			{ name: 'Djibouti' },
			{ name: 'Obock' },
			{ name: 'Tadjourah' },
		],
	},
	{
		name: 'Dominica',
		subregions: [
			{ name: 'Saint Andrew Parish' },
			{ name: 'Saint David Parish' },
			{ name: 'Saint George Parish' },
			{ name: 'Saint John Parish' },
			{ name: 'Saint Joseph Parish' },
			{ name: 'Saint Luke Parish' },
			{ name: 'Saint Mark Parish' },
			{ name: 'Saint Patrick Parish' },
			{ name: 'Saint Paul Parish' },
			{ name: 'Saint Peter Parish' },
		],
	},
	{
		name: 'Dominican Republic',
		subregions: [
			{ name: 'Azua' },
			{ name: 'Baoruco' },
			{ name: 'Barahona' },
			{ name: 'Dajabón' },
			{ name: 'Duarte' },
			{ name: 'El Seibo' },
			{ name: 'Elías Piña' },
			{ name: 'Espaillat' },
			{ name: 'Hato Mayor' },
			{ name: 'Hermanas Mirabal' },
			{ name: 'Independencia' },
			{ name: 'La Altagracia' },
			{ name: 'La Romana' },
			{ name: 'La Vega' },
			{ name: 'María Trinidad Sánchez' },
			{ name: 'Monseñor Nouel' },
			{ name: 'Monte Cristi' },
			{ name: 'Monte Plata' },
			{ name: 'Pedernales' },
			{ name: 'Peravia' },
			{ name: 'Puerto Plata' },
			{ name: 'Samaná' },
			{ name: 'San Cristóbal' },
			{ name: 'San José de Ocoa' },
			{ name: 'San Juan' },
			{ name: 'San Pedro de Macorís' },
			{ name: 'Sánchez Ramírez' },
			{ name: 'Santiago' },
			{ name: 'Santiago Rodríguez' },
			{ name: 'Santo Domingo' },
			{ name: 'Valverde' },
		],
	},
	{
		name: 'East Timor',
		subregions: [
			{ name: 'Aileu' },
			{ name: 'Ainaro' },
			{ name: 'Baucau' },
			{ name: 'Bobonaro' },
			{ name: 'Cova Lima' },
			{ name: 'Dili' },
			{ name: 'Ermera' },
			{ name: 'Lautém' },
			{ name: 'Liquiçá' },
			{ name: 'Manatuto' },
			{ name: 'Manufahi' },
			{ name: 'Oecusse' },
			{ name: 'Viqueque' },
		],
	},
	{
		name: 'Ecuador',
		subregions: [
			{ name: 'Azuay' },
			{ name: 'Bolívar' },
			{ name: 'Cañar' },
			{ name: 'Carchi' },
			{ name: 'Chimborazo' },
			{ name: 'Cotopaxi' },
			{ name: 'El Oro' },
			{ name: 'Esmeraldas' },
			{ name: 'Galápagos' },
			{ name: 'Guayas' },
			{ name: 'Imbabura' },
			{ name: 'Loja' },
			{ name: 'Los Ríos' },
			{ name: 'Manabí' },
			{ name: 'Morona Santiago' },
			{ name: 'Napo' },
			{ name: 'Orellana' },
			{ name: 'Pastaza' },
			{ name: 'Pichincha' },
			{ name: 'Santa Elena Province' },
			{ name: 'Santo Domingo de los Tsáchilas' },
			{ name: 'Sucumbíos' },
			{ name: 'Tungurahua' },
			{ name: 'Zamora Chinchipe' },
		],
	},
	{
		name: 'Egypt',
		subregions: [
			{ name: 'Al Sharqia Governorate' },
			{ name: 'Assouan' },
			{ name: 'Asyut Governorate' },
			{ name: 'Beheira Governorate' },
			{ name: 'Beni Suef Governorate' },
			{ name: 'Cairo Governorate' },
			{ name: 'Dakahlia Governorate' },
			{ name: 'Damietta Governorate' },
			{ name: 'Faiyum Governorate' },
			{ name: 'Gharbiyya Governorate' },
			{ name: 'Giza Governorate' },
			{ name: 'Ismailia' },
			{ name: 'Kafr el-Sheikh Governorate' },
			{ name: 'Luxor Governate' },
			{ name: 'Matrouh' },
			{ name: 'Minya Governate' },
			{ name: 'Monufia Governorate' },
			{ name: 'New Valley Governorate' },
			{ name: 'North Sinai' },
			{ name: 'Port Said' },
			{ name: 'Qalyubia Governorate' },
			{ name: 'Qena Governorate' },
			{ name: 'Red Sea Governorate' },
			{ name: 'Sohag Governorate' },
			{ name: 'South Sinai' },
			{ name: 'Suez Governorate' },
		],
	},
	{
		name: 'El Salvador',
		subregions: [
			{ name: 'Departamento de Ahuachapán' },
			{ name: 'Departamento de Cabañas' },
			{ name: 'Departamento de Chalatenango' },
			{ name: 'Departamento de Cuscatlán' },
			{ name: 'Departamento de La Paz' },
			{ name: 'Departamento de La Unión' },
			{ name: 'Departamento de Morazán' },
			{ name: 'Departamento de San Miguel' },
			{ name: 'Departamento de San Salvador' },
			{ name: 'Departamento de Santa Ana' },
			{ name: 'Departamento de Sonsonate' },
			{ name: 'Departamento de Usulután' },
			{ name: 'La Libertad' },
			{ name: 'San Vicente' },
		],
	},
	{
		name: 'Equatorial Guinea',
		subregions: [
			{ name: 'Annobón' },
			{ name: 'Bioko Norte' },
			{ name: 'Bioko Sur' },
			{ name: 'Centro Sur' },
			{ name: 'Kié-Ntem' },
			{ name: 'Litoral' },
			{ name: 'Wele-Nzas' },
		],
	},
	{
		name: 'Eritrea',
		subregions: [
			{ name: 'Anseba' },
			{ name: 'Debub Region' },
			{ name: 'Gash-Barka' },
			{ name: 'Maekel Region' },
			{ name: 'Northen Red Sea Region' },
		],
	},
	{
		name: 'Eswatini',
		subregions: [{ name: 'Hhohho' }, { name: 'Lubombo' }, { name: 'Manzini' }, { name: 'Shiselweni' }],
	},
	{
		name: 'Ethiopia',
		subregions: [
			{ name: 'Addis Ababa' },
			{ name: 'Afar Region' },
			{ name: 'Amhara Region' },
			{ name: 'Benishangul-Gumuz Region' },
			{ name: 'Dire Dawa' },
			{ name: 'Gambela Region' },
			{ name: 'Harar' },
			{ name: 'Oromia Region' },
			{ name: 'Sidama' },
			{ name: 'Somali Region' },
			{ name: 'Southern Nations' },
			{ name: 'Tigray' },
		],
	},
	{
		name: 'Faroe Islands',
		subregions: [
			{ name: 'Eysturoy region' },
			{ name: 'Norðoyar region' },
			{ name: 'Sandoy region' },
			{ name: 'Streymoy region' },
			{ name: 'Suðuroy region' },
			{ name: 'Vágar region' },
		],
	},
	{
		name: 'Federated States of Micronesia',
		subregions: [{ name: 'Chuuk' }, { name: 'Kosrae' }, { name: 'Pohnpei' }, { name: 'Yap' }],
	},
	{
		name: 'Fiji',
		subregions: [
			{ name: 'Central' },
			{ name: 'Eastern' },
			{ name: 'Northern' },
			{ name: 'Rotuma' },
			{ name: 'Western' },
		],
	},
	{
		name: 'France',
		subregions: [
			{ name: 'Auvergne-Rhône-Alpes' },
			{ name: 'Bourgogne-Franche-Comté' },
			{ name: 'Brittany' },
			{ name: 'Centre-Loire Valley' },
			{ name: 'Clipperton Island' },
			{ name: 'Corsica' },
			{ name: 'French Guiana' },
			{ name: 'Grand Est' },
			{ name: 'Guadeloupe' },
			{ name: 'Hauts-de-France' },
			{ name: 'Ile-de-France' },
			{ name: 'Martinique' },
			{ name: 'Mayotte' },
			{ name: 'New Aquitaine' },
			{ name: 'Normandy' },
			{ name: 'Occitania' },
			{ name: 'Pays de la Loire' },
			{ name: "Provence-Alpes-Côte d'Azur" },
			{ name: 'Réunion' },
			{ name: 'Tromelin Island' },
		],
	},
	{
		name: 'Gabon',
		subregions: [
			{ name: 'Estuaire' },
			{ name: 'Haut-Ogooué' },
			{ name: 'Moyen-Ogooué' },
			{ name: 'Ngounié' },
			{ name: 'Nyanga' },
			{ name: 'Ogooué-Ivindo' },
			{ name: 'Ogooué-Lolo' },
			{ name: 'Ogooué-Maritime' },
			{ name: 'Woleu-Ntem' },
		],
	},
	{
		name: 'Georgia',
		subregions: [
			{ name: 'Autonomous Republic of Abkhazia' },
			{ name: 'Autonomous Republic of Adjara' },
			{ name: 'Guria' },
			{ name: 'Imereti' },
			{ name: 'Inner Kartli' },
			{ name: 'Kakheti' },
			{ name: 'Lower Kartli' },
			{ name: 'Mtskheta-Mtianeti' },
			{ name: 'Racha-Lechkhumi and Lower Svaneti' },
			{ name: 'Samegrelo-Upper Svaneti' },
			{ name: 'Samtskhe-Javakheti' },
			{ name: 'Tbilisi' },
		],
	},
	{
		name: 'Germany',
		subregions: [
			{ name: 'Baden-Württemberg' },
			{ name: 'Bavaria' },
			{ name: 'Berlin' },
			{ name: 'Brandenburg' },
			{ name: 'Bremen' },
			{ name: 'Hamburg' },
			{ name: 'Hesse' },
			{ name: 'Lower Saxony' },
			{ name: 'Mecklenburg-Vorpommern' },
			{ name: 'North Rhine-Westphalia' },
			{ name: 'Rhineland-Palatinate' },
			{ name: 'Saarland' },
			{ name: 'Saxony' },
			{ name: 'Saxony-Anhalt' },
			{ name: 'Schleswig-Holstein' },
			{ name: 'Thuringia' },
		],
	},
	{
		name: 'Ghana',
		subregions: [
			{ name: 'Ahafo Region' },
			{ name: 'Ashanti Region' },
			{ name: 'Bono East Region' },
			{ name: 'Bono Region' },
			{ name: 'Central Region' },
			{ name: 'Eastern Region' },
			{ name: 'Greater Accra Region' },
			{ name: 'North East Region' },
			{ name: 'Northern Region' },
			{ name: 'Oti Region' },
			{ name: 'Savannah Region' },
			{ name: 'Upper West Region' },
			{ name: 'Volta Region' },
			{ name: 'Western North Region' },
			{ name: 'Western Region' },
		],
	},
	{ name: 'Gibraltar', subregions: [{ name: 'Gibraltar' }] },
	{
		name: 'Greece',
		subregions: [
			{ name: 'Aegean' },
			{ name: 'Attica' },
			{ name: 'Epirus and Western Macedonia' },
			{ name: 'Macedonia and Thrace' },
			{ name: 'Peloponnese, Western Greece and the Ionian' },
			{ name: 'Region of Crete' },
			{ name: 'Thessaly and Central Greece' },
		],
	},
	{
		name: 'Greenland',
		subregions: [
			{ name: 'Avannaata' },
			{ name: 'Kujalleq' },
			{ name: 'Pituffik' },
			{ name: 'Qeqertalik' },
			{ name: 'Qeqqata' },
			{ name: 'Sermersooq' },
		],
	},
	{
		name: 'Guatemala',
		subregions: [
			{ name: 'Alta Verapaz' },
			{ name: 'Baja Verapaz' },
			{ name: 'Chimaltenango' },
			{ name: 'Chiquimula' },
			{ name: 'Ciudad de Guatemala' },
			{ name: 'El Progreso' },
			{ name: 'Escuintla' },
			{ name: 'Guatemala' },
			{ name: 'Huehuetenango' },
			{ name: 'Izabal' },
			{ name: 'Jalapa' },
			{ name: 'Jutiapa' },
			{ name: 'Petén' },
			{ name: 'Quetzaltenango' },
			{ name: 'Quiché' },
			{ name: 'Retalhuleu' },
			{ name: 'Sacatepéquez' },
			{ name: 'San Marcos' },
			{ name: 'Santa Rosa' },
			{ name: 'Sololá' },
			{ name: 'Suchitepéquez' },
			{ name: 'Totonicapán' },
			{ name: 'Zacapa' },
		],
	},
	{ name: 'Guernsey', subregions: [{ name: 'Alderney' }, { name: 'Guernsey' }, { name: 'Sark' }] },
	{
		name: 'Guinea',
		subregions: [
			{ name: 'Boké' },
			{ name: 'Conakry' },
			{ name: 'Faranah' },
			{ name: 'Kankan' },
			{ name: 'Kindia' },
			{ name: 'Labé' },
			{ name: 'Mamou' },
			{ name: 'Nzérékoré' },
		],
	},
	{
		name: 'Guinea-Bissau',
		subregions: [
			{ name: 'Bissau Autonomous Sector' },
			{ name: 'Região de Bafatá' },
			{ name: 'Região de Biombo' },
			{ name: 'Região de Bolama' },
			{ name: 'Região de Cacheu' },
			{ name: 'Região de Gabu' },
			{ name: 'Região de Oio' },
			{ name: 'Região de Quinara' },
			{ name: 'Região de Tombali' },
		],
	},
	{
		name: 'Guyana',
		subregions: [
			{ name: 'Barima-Waini' },
			{ name: 'Cuyuni-Mazaruni' },
			{ name: 'Demerara-Mahaica' },
			{ name: 'East Berbice-Corentyne' },
			{ name: 'Essequibo Islands-West Demerara' },
			{ name: 'Mahaica-Berbice' },
			{ name: 'Pomeroon-Supenaam' },
			{ name: 'Potaro-Siparuni' },
			{ name: 'Upper Demerara-Berbice' },
			{ name: 'Upper Takutu-Upper Essequibo' },
		],
	},
	{
		name: 'Haiti',
		subregions: [
			{ name: 'Artibonite Department' },
			{ name: 'Centre Department' },
			{ name: "Département de l'Ouest" },
			{ name: 'Département de la Grande-Anse' },
			{ name: 'Département des Nippes' },
			{ name: 'Département du Nord' },
			{ name: 'Département du Sud-Est' },
			{ name: 'Île de la Navasse / Navassa Island' },
			{ name: 'Nord-Est Department' },
			{ name: 'Nord-Ouest Department' },
			{ name: 'Sud Department' },
		],
	},
	{
		name: 'Honduras',
		subregions: [
			{ name: 'Atlántida' },
			{ name: 'Bay Islands' },
			{ name: 'Beneficio de Café Memo' },
			{ name: 'Choluteca' },
			{ name: 'Colón' },
			{ name: 'Comayagua' },
			{ name: 'Copán' },
			{ name: 'Cortés' },
			{ name: 'El Paraíso' },
			{ name: 'Francisco Morazán' },
			{ name: 'Gracias a Dios' },
			{ name: 'Intibucá' },
			{ name: 'La Paz' },
			{ name: 'Lempira' },
			{ name: 'Ocotepeque' },
			{ name: 'Olancho' },
			{ name: 'Santa Bárbara' },
			{ name: 'Valle' },
			{ name: 'Yoro' },
		],
	},
	{
		name: 'Hungary',
		subregions: [{ name: 'Central Hungary' }, { name: 'Great Plain and North' }, { name: 'Transdanubia' }],
	},
	{
		name: 'India',
		subregions: [
			{ name: 'Andaman and Nicobar Islands' },
			{ name: 'Andhra Pradesh' },
			{ name: 'Assam' },
			{ name: 'Bihar' },
			{ name: 'Chandigarh' },
			{ name: 'Chhattisgarh' },
			{ name: 'Dadra and Nagar Haveli and Daman and Diu' },
			{ name: 'Delhi' },
			{ name: 'Goa' },
			{ name: 'Gujarat' },
			{ name: 'Haryana' },
			{ name: 'Himachal Pradesh' },
			{ name: 'Jammu and Kashmir' },
			{ name: 'Karnataka' },
			{ name: 'Kerala' },
			{ name: 'Lakshadweep' },
			{ name: 'Madhya Pradesh' },
			{ name: 'Maharashtra' },
			{ name: 'Manipur' },
			{ name: 'Meghalaya' },
			{ name: 'Mizoram' },
			{ name: 'Nagaland' },
			{ name: 'Odisha' },
			{ name: 'Puducherry' },
			{ name: 'Punjab' },
			{ name: 'Rajasthan' },
			{ name: 'Sikkim' },
			{ name: 'Tamil Nadu' },
			{ name: 'Telangana' },
			{ name: 'Tripura' },
			{ name: 'Uttar Pradesh' },
			{ name: 'Uttarakhand' },
		],
	},
	{
		name: 'Indonesia',
		subregions: [
			{ name: 'Aceh' },
			{ name: 'Bali' },
			{ name: 'Bangka-Belitung Islands' },
			{ name: 'Banten' },
			{ name: 'Bengkulu' },
			{ name: 'Central Java' },
			{ name: 'Central Kalimantan' },
			{ name: 'Central Sulawesi' },
			{ name: 'East Java' },
			{ name: 'East Kalimantan' },
			{ name: 'East Nusa Tenggara' },
			{ name: 'Gorontalo' },
			{ name: 'Jakarta Special Capital Region' },
			{ name: 'Jambi' },
			{ name: 'Lampung' },
			{ name: 'Maluku' },
			{ name: 'North Kalimantan' },
			{ name: 'North Maluku' },
			{ name: 'North Sulawesi' },
			{ name: 'North Sumatra' },
			{ name: 'Papua' },
			{ name: 'Riau' },
			{ name: 'Riau Islands' },
			{ name: 'South Kalimantan' },
			{ name: 'South Sulawesi' },
			{ name: 'South Sumatra' },
			{ name: 'Southeast Sulawesi' },
			{ name: 'Special Region of Yogyakarta' },
			{ name: 'West Java' },
			{ name: 'West Kalimantan' },
			{ name: 'West Nusa Tenggara' },
			{ name: 'West Papua' },
			{ name: 'West Sulawesi' },
			{ name: 'West Sumatra' },
		],
	},
	{
		name: 'Iran',
		subregions: [
			{ name: 'Alborz Province' },
			{ name: 'Ardabil Province' },
			{ name: 'Fars Province' },
			{ name: 'Gilan Province' },
			{ name: 'Hamadan Province' },
			{ name: 'Hormozgan Province' },
			{ name: 'Isfahan Province' },
			{ name: 'Khuzestan Province' },
			{ name: 'North Khorasan Province' },
			{ name: 'Qazvin Province' },
			{ name: 'Semnan Province' },
			{ name: 'Sistan and Baluchestan Province' },
			{ name: 'Tehran Province' },
			{ name: 'West Azerbaijan Province' },
			{ name: 'Zanjan Province' },
		],
	},
	{
		name: 'Iraq',
		subregions: [
			{ name: 'Al-Anbar Governorate' },
			{ name: 'Al-Basra Governorate' },
			{ name: 'Al-Muthanna Governorate' },
			{ name: 'Al-Najaf Governorate' },
			{ name: 'Al-Qadisiyah Governorate' },
			{ name: 'Babil Governorate' },
			{ name: 'Baghdad Governorate' },
			{ name: 'Dhi Qar Governorate' },
			{ name: 'Diyala Governorate' },
			{ name: 'Dohuk Governorate' },
			{ name: 'Erbil Governorate' },
			{ name: 'Halabja Governorate' },
			{ name: 'Karbala Governorate' },
			{ name: 'Kirkuk Governorate' },
			{ name: 'Maysan Governorate' },
			{ name: 'Nineveh Governorate' },
			{ name: 'Saladin Governorate' },
			{ name: 'Wasit Governorate' },
		],
	},
	{
		name: 'Israel',
		subregions: [
			{ name: 'Center District' },
			{ name: 'Haifa District' },
			{ name: 'Jerusalem District' },
			{ name: 'North District' },
			{ name: 'South District' },
			{ name: 'Tel Aviv District' },
		],
	},
	{
		name: 'Italy',
		subregions: [
			{ name: 'Abruzzo' },
			{ name: 'Aosta Valley' },
			{ name: 'Apulia' },
			{ name: 'Basilicata' },
			{ name: 'Calabria' },
			{ name: 'Campania' },
			{ name: 'Emilia-Romagna' },
			{ name: 'Friuli Venezia Giulia' },
			{ name: 'Lazio' },
			{ name: 'Liguria' },
			{ name: 'Lombardy' },
			{ name: 'Marche' },
			{ name: 'Molise' },
			{ name: 'Piemont' },
			{ name: 'Sardinia' },
			{ name: 'Sicily' },
			{ name: 'Trentino-Alto Adige/Südtirol' },
			{ name: 'Tuscany' },
			{ name: 'Umbria' },
			{ name: 'Veneto' },
		],
	},
	{
		name: 'Japan',
		subregions: [
			{ name: 'Aichi Prefecture' },
			{ name: 'Akita Prefecture' },
			{ name: 'Aomori Prefecture' },
			{ name: 'Chiba Prefecture' },
			{ name: 'Ehime Prefecture' },
			{ name: 'Fukui Prefecture' },
			{ name: 'Fukuoka Prefecture' },
			{ name: 'Fukushima Prefecture' },
			{ name: 'Gifu Prefecture' },
			{ name: 'Gunma Prefecture' },
			{ name: 'Hiroshima Prefecture' },
			{ name: 'Hokkaido Prefecture' },
			{ name: 'Hyogo Prefecture' },
			{ name: 'Ibaraki Prefecture' },
			{ name: 'Ishikawa Prefecture' },
			{ name: 'Iwate Prefecture' },
			{ name: 'Kagawa Prefecture' },
			{ name: 'Kagoshima Prefecture' },
			{ name: 'Kanagawa Prefecture' },
			{ name: 'Kochi Prefecture' },
			{ name: 'Kumamoto Prefecture' },
			{ name: 'Kyoto Prefecture' },
			{ name: 'Mie Prefecture' },
			{ name: 'Miyagi Prefecture' },
			{ name: 'Miyazaki Prefecture' },
			{ name: 'Nagano Prefecture' },
			{ name: 'Nagasaki Prefecture' },
			{ name: 'Nara Prefecture' },
			{ name: 'Niigata Prefecture' },
			{ name: 'Oita Prefecture' },
			{ name: 'Okayama Prefecture' },
			{ name: 'Okinawa Prefecture' },
			{ name: 'Osaka Prefecture' },
			{ name: 'Saga Prefecture' },
			{ name: 'Saitama Prefecture' },
			{ name: 'Shiga Prefecture' },
			{ name: 'Shimane Prefecture' },
			{ name: 'Shizuoka Prefecture' },
			{ name: 'Tochigi Prefecture' },
			{ name: 'Tokushima Prefecture' },
			{ name: 'Tokyo' },
			{ name: 'Tottori Prefecture' },
			{ name: 'Toyama Prefecture' },
			{ name: 'Wakayama Prefecture' },
			{ name: 'Yamagata Prefecture' },
			{ name: 'Yamaguchi Prefecture' },
			{ name: 'Yamanashi Prefecture' },
		],
	},
	{
		name: 'Jordan',
		subregions: [
			{ name: 'Ajlun' },
			{ name: 'Amman' },
			{ name: 'Aqaba' },
			{ name: 'Balqa' },
			{ name: 'Irbid' },
			{ name: 'Jarash' },
			{ name: 'Karak' },
			{ name: 'Maan' },
			{ name: 'Madaba' },
			{ name: 'Mafraq' },
			{ name: 'Tafilah' },
			{ name: 'Zarqa' },
		],
	},
	{
		name: 'Kazakhstan',
		subregions: [
			{ name: 'Akmola Region' },
			{ name: 'Aktobe Region' },
			{ name: 'Almaty' },
			{ name: 'Almaty Region' },
			{ name: 'Atyrau Region' },
			{ name: 'East Kazakhstan Region' },
			{ name: 'Jambyl Region' },
			{ name: 'Karaganda Region' },
			{ name: 'Kostanay Region' },
			{ name: 'Kyzylorda Region' },
			{ name: 'Mangystau Region' },
			{ name: 'North Kazakhstan Region' },
			{ name: 'Nur-Sultan' },
			{ name: 'Pavlodar Region' },
			{ name: 'Turkistan Region' },
			{ name: 'West Kazakhstan Region' },
			{ name: 'Шымкент' },
		],
	},
	{
		name: 'Kenya',
		subregions: [
			{ name: 'Baringo' },
			{ name: 'Bomet' },
			{ name: 'Bungoma' },
			{ name: 'Busia' },
			{ name: 'Elgeyo-Marakwet' },
			{ name: 'Embu County' },
			{ name: 'Garissa County' },
			{ name: 'Homa Bay' },
			{ name: 'Isiolo County' },
			{ name: 'Kajiado County' },
			{ name: 'Kakamega' },
			{ name: 'Kericho' },
			{ name: 'Kiambu County' },
			{ name: 'Kilifi' },
			{ name: 'Kirinyaga County' },
			{ name: 'Kisii' },
			{ name: 'Kisumu' },
			{ name: 'Kitui' },
			{ name: 'Kwale' },
			{ name: 'Laikipia' },
			{ name: 'Lamu' },
			{ name: 'Machakos' },
			{ name: 'Makueni' },
			{ name: 'Mandera' },
			{ name: 'Marsabit' },
			{ name: 'Meru' },
			{ name: 'Migori' },
			{ name: 'Mombasa' },
			{ name: 'Murang`a' },
			{ name: 'Nairobi' },
			{ name: 'Nakuru' },
			{ name: 'Nandi' },
			{ name: 'Narok' },
			{ name: 'Nyamira' },
			{ name: 'Nyandarua' },
			{ name: 'Nyeri' },
			{ name: 'Samburu' },
			{ name: 'Siaya' },
			{ name: 'Taita Taveta' },
			{ name: 'Tana River' },
			{ name: 'Tharaka-Nithi' },
			{ name: 'Trans Nzoia' },
			{ name: 'Turkana' },
			{ name: 'Uasin Gishu' },
			{ name: 'Vihiga' },
			{ name: 'Wajir' },
			{ name: 'West Pokot' },
		],
	},
	{
		name: 'Kuwait',
		subregions: [
			{ name: 'Ahmadi' },
			{ name: 'Al Asimah' },
			{ name: 'Farwaniya' },
			{ name: 'Hawalli' },
			{ name: 'Jahra' },
			{ name: 'Mubarak Al-Kabeer' },
		],
	},
	{
		name: 'Kyrgyzstan',
		subregions: [
			{ name: 'Batken Region' },
			{ name: 'Bishkek' },
			{ name: 'Chuy Region' },
			{ name: 'City of Osh' },
			{ name: 'Issyk-Kul Region' },
			{ name: 'Jalal-Abad Region' },
			{ name: 'Naryn Region' },
			{ name: 'Osh Region' },
			{ name: 'Talas Region' },
		],
	},
	{
		name: 'Laos',
		subregions: [
			{ name: 'Attapeu' },
			{ name: 'Bokeo Province' },
			{ name: 'Bolikhamsai' },
			{ name: 'Champasak Province' },
			{ name: 'Houaphanh' },
			{ name: 'Khammouane' },
			{ name: 'Luang Namtha' },
			{ name: 'Luang Prabang' },
			{ name: 'Oudomxay' },
			{ name: 'Phongsaly' },
			{ name: 'Sainyabuli Province' },
			{ name: 'Salavan Province' },
			{ name: 'Savannakhet Province' },
			{ name: 'Sekong Province' },
			{ name: 'Vientiane Prefecture' },
			{ name: 'Vientiane Province' },
			{ name: 'Xaisomboun Province' },
			{ name: 'Xiangkhouang Province' },
		],
	},
	{
		name: 'Latvia',
		subregions: [{ name: 'Courland' }, { name: 'Latgale' }, { name: 'Vidzeme' }, { name: 'Zemgale' }],
	},
	{
		name: 'Lebanon',
		subregions: [
			{ name: 'Akkar Governorate' },
			{ name: 'Baalbek-Hermel Governorate' },
			{ name: 'Beirut Governorate' },
			{ name: 'Beqaa Governorate' },
			{ name: 'Mount Lebanon Governorate' },
			{ name: 'Nabatiya Governorate' },
			{ name: 'North Governorate' },
			{ name: 'South Governorate' },
		],
	},
	{
		name: 'Liberia',
		subregions: [
			{ name: 'Bomi County' },
			{ name: 'Bong County' },
			{ name: 'Gbarpolu County' },
			{ name: 'Grand Bassa County' },
			{ name: 'Grand Cape Mount County' },
			{ name: 'Grand Gedeh County' },
			{ name: 'Grand Kru County' },
			{ name: 'Lofa County' },
			{ name: 'Margibi County' },
			{ name: 'Maryland County' },
			{ name: 'Montserrado County' },
			{ name: 'Nimba County' },
			{ name: 'River Cess County' },
			{ name: 'River Gee County' },
			{ name: 'Sinoe County' },
		],
	},
	{
		name: 'Libya',
		subregions: [
			{ name: 'Al Wahat' },
			{ name: 'Benghazi' },
			{ name: 'Butnan' },
			{ name: 'Derna' },
			{ name: 'Ghat' },
			{ name: 'Jabal al Akhdar' },
			{ name: 'Jabal al Gharbi' },
			{ name: 'Jafara' },
			{ name: 'Jufra' },
			{ name: 'Kufra' },
			{ name: 'Marj' },
			{ name: 'Murqub' },
			{ name: 'Murzuq' },
			{ name: 'Nalut' },
			{ name: 'Nuqat al Khams' },
			{ name: 'Sabha' },
			{ name: 'Sirte' },
			{ name: 'Tripoli' },
			{ name: 'Wadi al Hayaa' },
			{ name: 'Wadi al Shatii' },
			{ name: 'Zawiya' },
		],
	},
	{
		name: 'Lithuania',
		subregions: [
			{ name: 'Alytus County' },
			{ name: 'Kaunas County' },
			{ name: 'Klaipeda County' },
			{ name: 'Marijampole County' },
			{ name: 'Panevezys County' },
			{ name: 'Siauliai County' },
			{ name: 'Taurage County' },
			{ name: 'Telsiai County' },
			{ name: 'Utena County' },
			{ name: 'Vilnius County' },
		],
	},
	{
		name: 'Madagascar',
		subregions: [
			{ name: 'Alaotra-Mangoro' },
			{ name: "Amoron'i Mania" },
			{ name: 'Analamanga' },
			{ name: 'Analanjirofo' },
			{ name: 'Androy' },
			{ name: 'Anosy' },
			{ name: 'Atsimo-Andrefana' },
			{ name: 'Atsimo-Atsinanana' },
			{ name: 'Atsinanana' },
			{ name: 'Betsiboka' },
			{ name: 'Boeny' },
			{ name: 'Bongolava' },
			{ name: 'Diana' },
			{ name: 'Ihorombe' },
			{ name: 'Itasy' },
			{ name: 'Matsiatra Ambony' },
			{ name: 'Melaky' },
			{ name: 'Menabe' },
			{ name: 'Sava' },
			{ name: 'Sofia' },
			{ name: 'Vakinankaratra' },
			{ name: 'Vatovavy-Fitovinany' },
		],
	},
	{
		name: 'Malawi',
		subregions: [
			{ name: 'Balaka' },
			{ name: 'Blantyre' },
			{ name: 'Chikwawa' },
			{ name: 'Chiradzulu' },
			{ name: 'Chitipa' },
			{ name: 'Dedza' },
			{ name: 'Dowa' },
			{ name: 'Karonga' },
			{ name: 'Kasungu' },
			{ name: 'Likoma' },
			{ name: 'Lilongwe' },
			{ name: 'Machinga' },
			{ name: 'Mangochi' },
			{ name: 'Mchinji' },
			{ name: 'Mulanje' },
			{ name: 'Mwanza' },
			{ name: 'Mzimba' },
			{ name: 'Neno' },
			{ name: 'Nkhata Bay' },
			{ name: 'Nkhotakota' },
			{ name: 'Nsanje' },
			{ name: 'Ntcheu' },
			{ name: 'Ntchisi' },
			{ name: 'Phalombe' },
			{ name: 'Rumphi' },
			{ name: 'Salima' },
			{ name: 'Thyolo' },
			{ name: 'Zomba' },
		],
	},
	{
		name: 'Malaysia',
		subregions: [
			{ name: 'Johor' },
			{ name: 'Kedah' },
			{ name: 'Kelantan' },
			{ name: 'Kuala Lumpur' },
			{ name: 'Labuan' },
			{ name: 'Malacca' },
			{ name: 'Negeri Sembilan' },
			{ name: 'Pahang' },
			{ name: 'Penang' },
			{ name: 'Perak' },
			{ name: 'Perlis' },
			{ name: 'Putrajaya' },
			{ name: 'Sabah' },
			{ name: 'Sarawak' },
			{ name: 'Selangor' },
			{ name: 'Terengganu' },
		],
	},
	{
		name: 'Maldives',
		subregions: [
			{ name: 'Addu' },
			{ name: 'Alif Alif' },
			{ name: 'Alif Dhaalu' },
			{ name: 'Baa' },
			{ name: 'Dhaalu' },
			{ name: 'Faafu' },
			{ name: 'Gaafu Alif' },
			{ name: 'Gaafu Dhaalu' },
			{ name: 'Gnaviyani' },
			{ name: 'Haa Alif' },
			{ name: 'Haa Dhaalu' },
			{ name: 'Kaafu' },
			{ name: 'Laamu' },
			{ name: 'Lhaviyani' },
			{ name: 'Malé' },
			{ name: 'Meemu' },
			{ name: 'Noonu' },
			{ name: 'Raa' },
			{ name: 'Shaviyani' },
			{ name: 'Thaa' },
			{ name: 'Vaavu' },
		],
	},
	{
		name: 'Mali',
		subregions: [
			{ name: 'Bamako' },
			{ name: 'Gao' },
			{ name: 'Kayes' },
			{ name: 'Kidal' },
			{ name: 'Koulikoro' },
			{ name: 'Ménaka' },
			{ name: 'Sikasso' },
			{ name: 'Timbuktu' },
		],
	},
	{
		name: 'Malta',
		subregions: [
			{ name: 'Central Region' },
			{ name: 'Gozo Region' },
			{ name: 'Northern Region' },
			{ name: 'South Eastern Region' },
			{ name: 'Southern Region' },
		],
	},
	{
		name: 'Mauritania',
		subregions: [
			{ name: 'Adrar' },
			{ name: 'Assaba' },
			{ name: 'Brakna' },
			{ name: 'Gorgol' },
			{ name: 'Guidimaka' },
			{ name: 'Hodh Ech Chargui' },
			{ name: 'Hodh El Gharbi' },
			{ name: 'Inchiri' },
			{ name: 'Nouakchott' },
			{ name: 'Tagant' },
			{ name: 'Tiris Zemmour' },
			{ name: 'Trarza' },
			{ name: 'Wilaya Dakhlet Nouadhibou' },
		],
	},
	{
		name: 'Mauritius',
		subregions: [
			{ name: 'Black River' },
			{ name: 'Flacq' },
			{ name: 'Grand Port' },
			{ name: 'Moka' },
			{ name: 'Pamplemousses' },
			{ name: 'Plaines Wilhems' },
			{ name: 'Port Louis' },
			{ name: 'Rivière du Rempart' },
			{ name: 'Rodrigues' },
			{ name: 'Savanne' },
		],
	},
	{
		name: 'Mexico',
		subregions: [
			{ name: 'Aguascalientes' },
			{ name: 'Baja California' },
			{ name: 'Baja California Sur' },
			{ name: 'Campeche' },
			{ name: 'Chiapas' },
			{ name: 'Chihuahua' },
			{ name: 'Coahuila' },
			{ name: 'Colima' },
			{ name: 'Durango' },
			{ name: 'Guanajuato' },
			{ name: 'Guerrero' },
			{ name: 'Hidalgo' },
			{ name: 'Isla Isabela' },
			{ name: 'Jalisco' },
			{ name: 'Mexico City' },
			{ name: 'Michoacán' },
			{ name: 'Morelos' },
			{ name: 'Nayarit' },
			{ name: 'Nuevo León' },
			{ name: 'Oaxaca' },
			{ name: 'Puebla' },
			{ name: 'Querétaro' },
			{ name: 'Quintana Roo' },
			{ name: 'San Luis Potosi' },
			{ name: 'Sinaloa' },
			{ name: 'Sonora' },
			{ name: 'State of Mexico' },
			{ name: 'Tabasco' },
			{ name: 'Tamaulipas' },
			{ name: 'Tlaxcala' },
			{ name: 'Veracruz' },
			{ name: 'Yucatán' },
			{ name: 'Zacatecas' },
		],
	},
	{
		name: 'Moldova',
		subregions: [
			{ name: 'Administrative-Territorial Units from the Left Bank of the Dniester' },
			{ name: 'Anenii Noi District' },
			{ name: 'Bălți Municipality' },
			{ name: 'Basarabeasca District' },
			{ name: 'Bender Municipality' },
			{ name: 'Briceni District' },
			{ name: 'Cahul District' },
			{ name: 'Calarași District' },
			{ name: 'Cantemir District' },
			{ name: 'Căușeni District' },
			{ name: 'Chișinău Municipality' },
			{ name: 'Cimișlia District' },
			{ name: 'Criuleni District' },
			{ name: 'Dondușeni District' },
			{ name: 'Drochia District' },
			{ name: 'Dubăsari District' },
			{ name: 'Edineț District' },
			{ name: 'Fălești District' },
			{ name: 'Florești District' },
			{ name: 'Gagauzia' },
			{ name: 'Glodeni District' },
			{ name: 'Hîncești District' },
			{ name: 'Ialoveni District' },
			{ name: 'Leova District' },
			{ name: 'Nisporeni District' },
			{ name: 'Ocnița District' },
			{ name: 'Orhei District' },
			{ name: 'Rezina District' },
			{ name: 'Rîșcani District' },
			{ name: 'Sîngerei District' },
			{ name: 'Șoldănești District' },
			{ name: 'Soroca District' },
			{ name: 'Ștefan Vodă District' },
			{ name: 'Strășeni District' },
			{ name: 'Taraclia District' },
			{ name: 'Telenești District' },
			{ name: 'Ungheni District' },
		],
	},
	{
		name: 'Mongolia',
		subregions: [
			{ name: 'Arkhangai' },
			{ name: 'Bayan-Ölgii' },
			{ name: 'Bayankhongor' },
			{ name: 'Bulgan' },
			{ name: 'Darkhan-Uul' },
			{ name: 'Dornod' },
			{ name: 'Dornogovi' },
			{ name: 'Dundgovi' },
			{ name: 'Govi-Altai' },
			{ name: 'Govisumber' },
			{ name: 'Hovsgel' },
			{ name: 'Khentii' },
			{ name: 'Khovd' },
			{ name: 'Ömnögovi' },
			{ name: 'Orkhon' },
			{ name: 'Övörkhangai' },
			{ name: 'Selenge' },
			{ name: 'Sükhbaatar' },
			{ name: 'Töv' },
			{ name: 'Ulaanbaatar' },
			{ name: 'Uvs' },
			{ name: 'Zavkhan' },
		],
	},
	{
		name: 'Morocco',
		subregions: [
			{ name: 'Béni Mellal-Khénifra' },
			{ name: 'Casablanca-Settat' },
			{ name: 'Drâa-Tafilalet' },
			{ name: 'Fez-Meknes' },
			{ name: 'Marrakech-Safi' },
			{ name: 'Oriental' },
			{ name: 'Rabat-Salé-Kenitra' },
			{ name: 'Souss-Massa' },
			{ name: 'Tangier-Tetouan-Al Hoceima' },
		],
	},
	{
		name: 'Mozambique',
		subregions: [
			{ name: 'Cabo Delgado' },
			{ name: 'Cidade de Maputo' },
			{ name: 'Gaza' },
			{ name: 'Inhambane' },
			{ name: 'Manica' },
			{ name: 'Maputo' },
			{ name: 'Matola' },
			{ name: 'Nampula' },
			{ name: 'Niassa' },
			{ name: 'Sofala' },
			{ name: 'Tete' },
			{ name: 'Zambézia' },
		],
	},
	{
		name: 'Myanmar',
		subregions: [
			{ name: 'Ayeyarwady' },
			{ name: 'Bago Region' },
			{ name: 'Chin' },
			{ name: 'Kachin' },
			{ name: 'Kayah' },
			{ name: 'Kayin' },
			{ name: 'Magway' },
			{ name: 'Mandalay' },
			{ name: 'Mon' },
			{ name: 'Naypyitaw' },
			{ name: 'Rakhine' },
			{ name: 'Sagaing' },
			{ name: 'Shan State' },
			{ name: 'Tanintharyi Region' },
			{ name: 'Yangon' },
		],
	},
	{
		name: 'Namibia',
		subregions: [
			{ name: 'Arandis' },
			{ name: 'Aranos7' },
			{ name: 'Erongo Region' },
			{ name: 'Hardap' },
			{ name: 'Karas' },
			{ name: 'Kavango East' },
			{ name: 'Kavango West' },
			{ name: 'Khomas' },
			{ name: 'Kunene Region' },
			{ name: 'Ohangwena' },
			{ name: 'Omaheke' },
			{ name: 'Omusati' },
			{ name: 'Oshana' },
			{ name: 'Oshikoto' },
			{ name: 'Otjozondjupa' },
			{ name: 'Zambezi' },
		],
	},
	{
		name: 'Nepal',
		subregions: [{ name: 'Far-Western Development Region' }, { name: 'Mid-Western Development Region' }],
	},
	{
		name: 'Netherlands',
		subregions: [
			{ name: 'Drenthe' },
			{ name: 'Flevoland' },
			{ name: 'Friesland' },
			{ name: 'Gelderland' },
			{ name: 'Groningen' },
			{ name: 'Limburg' },
			{ name: 'North Brabant' },
			{ name: 'North Holland' },
			{ name: 'Overijssel' },
			{ name: 'South Holland' },
			{ name: 'Utrecht' },
			{ name: 'Zeeland' },
		],
	},
	{
		name: 'New Zealand',
		subregions: [
			{ name: 'Auckland' },
			{ name: 'Bay of Plenty' },
			{ name: 'Canterbury' },
			{ name: 'Chatham Islands' },
			{ name: 'Gisborne' },
			{ name: "Hawke's Bay" },
			{ name: 'Manawatu-Whanganui' },
			{ name: 'Marlborough' },
			{ name: 'Nelson' },
			{ name: 'Northland' },
			{ name: 'Otago' },
			{ name: 'Southland' },
			{ name: 'Taranaki' },
			{ name: 'Tasman' },
			{ name: 'Waikato' },
			{ name: 'Wellington' },
			{ name: 'West Coast' },
		],
	},
	{
		name: 'Nicaragua',
		subregions: [
			{ name: 'Boaco' },
			{ name: 'Carazo' },
			{ name: 'Chinandega' },
			{ name: 'Chontales' },
			{ name: 'Departamento de Managua' },
			{ name: 'Estelí' },
			{ name: 'Granada' },
			{ name: 'Jinotega' },
			{ name: 'Leon' },
			{ name: 'Madriz' },
			{ name: 'Masaya' },
			{ name: 'Matagalpa' },
			{ name: 'North Carribean Coast Autonomous Region' },
			{ name: 'Nueva Segovia' },
			{ name: 'Rio San Juan' },
			{ name: 'Rivas' },
			{ name: 'South Atlantic Autonomous Region' },
		],
	},
	{
		name: 'Niger',
		subregions: [
			{ name: 'Agadez' },
			{ name: 'Diffa' },
			{ name: 'Dosso' },
			{ name: 'Maradi' },
			{ name: 'Niamey' },
			{ name: 'Tahoua' },
			{ name: 'Tillabéri' },
			{ name: 'Zinder' },
		],
	},
	{
		name: 'Nigeria',
		subregions: [
			{ name: 'Abia' },
			{ name: 'Adamawa' },
			{ name: 'Akwa Ibom' },
			{ name: 'Anambra' },
			{ name: 'Bauchi' },
			{ name: 'Bayelsa' },
			{ name: 'Benue' },
			{ name: 'Borno' },
			{ name: 'Cross River' },
			{ name: 'Delta' },
			{ name: 'Ebonyi' },
			{ name: 'Edo' },
			{ name: 'Ekiti' },
			{ name: 'Enugu' },
			{ name: 'Federal Capital Territory' },
			{ name: 'Gombe' },
			{ name: 'Imo' },
			{ name: 'Jigawa' },
			{ name: 'Kaduna' },
			{ name: 'Kano' },
			{ name: 'Katsina' },
			{ name: 'Kebbi' },
			{ name: 'Kogi' },
			{ name: 'Kwara' },
			{ name: 'Nasarawa' },
			{ name: 'Niger' },
			{ name: 'Ogun' },
			{ name: 'Ondo' },
			{ name: 'Osun' },
			{ name: 'Oyo' },
			{ name: 'Plateau' },
			{ name: 'Rivers' },
			{ name: 'Sokoto' },
			{ name: 'Taraba' },
			{ name: 'Yobe' },
			{ name: 'Zamfara' },
		],
	},
	{
		name: 'North Korea',
		subregions: [
			{ name: 'Chagang' },
			{ name: 'Hamgyongnam-do' },
			{ name: 'Hwanghaenam-do' },
			{ name: 'Kangwon-do' },
			{ name: 'Nampo' },
			{ name: 'North Hamgyong' },
			{ name: 'North Hwanghae Province' },
			{ name: 'North Pyongan' },
			{ name: 'Pyongannam-do' },
			{ name: 'Pyongyang' },
			{ name: 'Rason' },
			{ name: 'Ryanggang' },
			{ name: '평양시' },
		],
	},
	{
		name: 'North Macedonia',
		subregions: [
			{ name: 'Eastern Region' },
			{ name: 'Northeastern Region' },
			{ name: 'Pelagonia Region' },
			{ name: 'Polog Region' },
			{ name: 'Skopje Region' },
			{ name: 'Southeastern Region' },
			{ name: 'Southwestern Region' },
			{ name: 'Vardar Region' },
		],
	},
	{
		name: 'Norway',
		subregions: [
			{ name: 'Agder' },
			{ name: 'Bouvet Island' },
			{ name: 'Innlandet' },
			{ name: 'Jan Mayen' },
			{ name: 'Møre og Romsdal' },
			{ name: 'Nordland' },
			{ name: 'Oslo' },
			{ name: 'Rogaland' },
			{ name: 'Svalbard' },
			{ name: 'Troms og Finnmark' },
			{ name: 'Trøndelag' },
			{ name: 'Vestfold og Telemark' },
			{ name: 'Vestland' },
			{ name: 'Viken' },
		],
	},
	{
		name: 'Oman',
		subregions: [
			{ name: 'Ad Dakhiliyah Governorate' },
			{ name: 'Ad Dhahirah Governorate' },
			{ name: 'Al Batinah North Governorate' },
			{ name: 'Al Batinah South Governorate' },
			{ name: 'Al Buraymi Governorate' },
			{ name: 'Al Wusta Governorate' },
			{ name: 'Ash Sharqiyah North' },
			{ name: 'Ash Sharqiyah South' },
			{ name: 'Dhofar' },
			{ name: 'Musandam Governorate' },
			{ name: 'Muscat' },
		],
	},
	{
		name: 'Pakistan',
		subregions: [
			{ name: 'Bagh District' },
			{ name: 'Bhimber District' },
			{ name: 'Chaklala Cantt' },
			{ name: 'District Attock' },
			{ name: 'Haveli District' },
			{ name: 'Jhelum District' },
			{ name: 'Jhelum Valley District' },
			{ name: 'Kotli District' },
			{ name: 'Mirpur District' },
			{ name: 'Muzaffarabad Districts' },
			{ name: 'Poonch District' },
			{ name: 'Rawalpindi Cantt' },
			{ name: 'Rawalpindi District' },
			{ name: 'Sudhanoti District' },
			{ name: 'Taxila Tehsil' },
			{ name: 'Tehsil Sohawa' },
		],
	},
	{
		name: 'Palau',
		subregions: [
			{ name: 'Aimeliik' },
			{ name: 'Airai' },
			{ name: 'Angaur' },
			{ name: 'Hatohobei' },
			{ name: 'Kayangel' },
			{ name: 'Koror' },
			{ name: 'Melekeok' },
			{ name: 'Ngaraard' },
			{ name: 'Ngarchelong' },
			{ name: 'Ngardmau' },
			{ name: 'Ngatpang' },
			{ name: 'Ngchesar' },
			{ name: 'Ngeremlengui' },
			{ name: 'Ngiwal' },
			{ name: 'Peleliu' },
			{ name: 'Sonsorol' },
		],
	},
	{
		name: 'Panama',
		subregions: [
			{ name: 'Bocas del Toro' },
			{ name: 'Chiriquí' },
			{ name: 'Coclé' },
			{ name: 'Colón' },
			{ name: 'Comarca Emberá-Wounaan' },
			{ name: 'Comarca Guna Yala' },
			{ name: 'Comarca Ngäbe Buglé' },
			{ name: 'Darién' },
			{ name: 'Herrera' },
			{ name: 'Los Santos' },
			{ name: 'Panamá' },
			{ name: 'Panamá Oeste' },
			{ name: 'Veraguas' },
		],
	},
	{
		name: 'Papua New Guinea',
		subregions: [
			{ name: 'Autonomous Region of Bougainville' },
			{ name: 'Central' },
			{ name: 'East New Britain' },
			{ name: 'East Sepik' },
			{ name: 'Eastern Highlands' },
			{ name: 'Enga' },
			{ name: 'Gulf' },
			{ name: 'Hela' },
			{ name: 'Jiwaka' },
			{ name: 'Madang' },
			{ name: 'Manus' },
			{ name: 'Milne Bay' },
			{ name: 'Morobe' },
			{ name: 'National Capital District' },
			{ name: 'New Ireland' },
			{ name: 'Oro' },
			{ name: 'Sandaun' },
			{ name: 'Simbu' },
			{ name: 'Southern Highlands' },
			{ name: 'West New Britain' },
			{ name: 'Western' },
			{ name: 'Western Highlands' },
		],
	},
	{
		name: 'Paraguay',
		subregions: [
			{ name: 'Alto Paraguay' },
			{ name: 'Alto Paraná' },
			{ name: 'Amambay' },
			{ name: 'Boquerón' },
			{ name: 'Caaguazú' },
			{ name: 'Caazapá' },
			{ name: 'Canindeyú' },
			{ name: 'Central' },
			{ name: 'Concepción' },
			{ name: 'Cordillera' },
			{ name: 'Guairá' },
			{ name: 'Paraguarí' },
			{ name: 'Presidente Hayes' },
			{ name: 'San Pedro' },
		],
	},
	{
		name: 'Peru',
		subregions: [
			{ name: 'Amazonas' },
			{ name: 'Ancash' },
			{ name: 'Apurímac' },
			{ name: 'Arequipa' },
			{ name: 'Ayacucho' },
			{ name: 'Cajamarca' },
			{ name: 'Callao' },
			{ name: 'Cusco' },
			{ name: 'Huancavelica' },
			{ name: 'Huánuco' },
			{ name: 'Ica' },
			{ name: 'Junín' },
			{ name: 'La Libertad' },
			{ name: 'Lambayeque' },
			{ name: 'Lima' },
			{ name: 'Loreto' },
			{ name: 'Madre de Dios' },
			{ name: 'Moquegua' },
			{ name: 'Pasco' },
			{ name: 'Piura' },
			{ name: 'Puno' },
			{ name: 'San Martín' },
			{ name: 'Tacna' },
			{ name: 'Tumbes' },
			{ name: 'Ucayali' },
		],
	},
	{
		name: 'Philippines',
		subregions: [
			{ name: 'Abra' },
			{ name: 'Agusan del Norte' },
			{ name: 'Agusan del Sur' },
			{ name: 'Aklan' },
			{ name: 'Albay' },
			{ name: 'Antique' },
			{ name: 'Apayao' },
			{ name: 'Aurora' },
			{ name: 'Basilan' },
			{ name: 'Bataan' },
			{ name: 'Batanes' },
			{ name: 'Batangas' },
			{ name: 'Benguet' },
			{ name: 'Biliran' },
			{ name: 'Bukidnon' },
			{ name: 'Bulacan' },
			{ name: 'Cagayan' },
			{ name: 'Camarines Norte' },
			{ name: 'Camarines Sur' },
			{ name: 'Camiguin' },
			{ name: 'Capiz' },
			{ name: 'Catanduanes' },
			{ name: 'Cavite' },
			{ name: 'Cebu' },
			{ name: 'Cotabato' },
			{ name: 'Davao de Oro' },
			{ name: 'Davao del Norte' },
			{ name: 'Davao del Sur' },
			{ name: 'Davao Occidental' },
			{ name: 'Davao Oriental' },
			{ name: 'Dinagat Islands' },
			{ name: 'Eastern Samar' },
			{ name: 'Guimaras' },
			{ name: 'Ifugao' },
			{ name: 'Ilocos Norte' },
			{ name: 'Ilocos Sur' },
			{ name: 'Iloilo' },
			{ name: 'Isabela' },
			{ name: 'La Union' },
			{ name: 'Laguna' },
			{ name: 'Lanao del Norte' },
			{ name: 'Lanao del Sur' },
			{ name: 'Leyte' },
			{ name: 'Maguindanao' },
			{ name: 'Marinduque' },
			{ name: 'Masbate' },
			{ name: 'Misamis Occidental' },
			{ name: 'Misamis Oriental' },
			{ name: 'Mountain Province' },
			{ name: 'Negros Occidental' },
			{ name: 'Negros Oriental' },
			{ name: 'Northern Samar' },
			{ name: 'Nueva Ecija' },
			{ name: 'Nueva Vizcaya' },
			{ name: 'Occidental Mindoro' },
			{ name: 'Oriental Mindoro' },
			{ name: 'Palawan' },
			{ name: 'Pampanga' },
			{ name: 'Pangasinan' },
			{ name: 'Quezon' },
			{ name: 'Quirino' },
			{ name: 'Rizal' },
			{ name: 'Romblon' },
			{ name: 'Samar' },
			{ name: 'Sarangani' },
			{ name: 'Siquijor' },
			{ name: 'Sorsogon' },
			{ name: 'South Cotabato' },
			{ name: 'Southern Leyte' },
			{ name: 'Sultan Kudarat' },
			{ name: 'Sulu' },
			{ name: 'Surigao del Norte' },
			{ name: 'Surigao del Sur' },
			{ name: 'Tarlac' },
			{ name: 'Tawi-Tawi' },
			{ name: 'Zambales' },
			{ name: 'Zamboanga del Norte' },
			{ name: 'Zamboanga del Sur' },
			{ name: 'Zamboanga Sibugay' },
		],
	},
	{
		name: 'Poland',
		subregions: [
			{ name: 'Greater Poland Voivodeship' },
			{ name: 'Kuyavian-Pomeranian Voivodeship' },
			{ name: 'Lesser Poland Voivodeship' },
			{ name: 'Łódź Voivodeship' },
			{ name: 'Lower Silesian Voivodeship' },
			{ name: 'Lublin Voivodeship' },
			{ name: 'Lubusz Voivodeship' },
			{ name: 'Masovian Voivodeship' },
			{ name: 'Opole Voivodeship' },
			{ name: 'Podlaskie Voivodeship' },
			{ name: 'Pomeranian Voivodeship' },
			{ name: 'Silesian Voivodeship' },
			{ name: 'Subcarpathian Voivodeship' },
			{ name: 'Świętokrzyskie Voivodeship' },
			{ name: 'Warmian-Masurian Voivodeship' },
			{ name: 'West Pomeranian Voivodeship' },
		],
	},
	{
		name: 'Portugal',
		subregions: [
			{ name: 'Alentejo' },
			{ name: 'Algarve' },
			{ name: 'Área Metropolitana de Lisboa' },
			{ name: 'Azores' },
			{ name: 'Centro' },
			{ name: 'Madeira' },
			{ name: 'North' },
		],
	},
	{
		name: 'Qatar',
		subregions: [
			{ name: 'Al Daayen' },
			{ name: 'Al Khor and Al Thakhira' },
			{ name: 'Al Shahaniya' },
			{ name: 'Al Wakrah' },
			{ name: 'Ar Rayyan' },
			{ name: 'Ash Shamal' },
			{ name: 'Doha' },
			{ name: 'Umm Salal' },
		],
	},
	{
		name: 'Romania',
		subregions: [
			{ name: 'Alba' },
			{ name: 'Arad' },
			{ name: 'Argeș' },
			{ name: 'Bacău' },
			{ name: 'Bihor' },
			{ name: 'Bistrița-Năsăud' },
			{ name: 'Botoșani' },
			{ name: 'Brăila' },
			{ name: 'Brașov' },
			{ name: 'Bucharest' },
			{ name: 'Buzău' },
			{ name: 'Călărași' },
			{ name: 'Caraș-Severin' },
			{ name: 'Cluj' },
			{ name: 'Constanța' },
			{ name: 'Covasna' },
			{ name: 'Dâmbovița' },
			{ name: 'Dolj' },
			{ name: 'Galați' },
			{ name: 'Giurgiu' },
			{ name: 'Gorj' },
			{ name: 'Harghita' },
			{ name: 'Hunedoara' },
			{ name: 'Ialomița' },
			{ name: 'Iași' },
			{ name: 'Ilfov' },
			{ name: 'Maramureș' },
			{ name: 'Mehedinți' },
			{ name: 'Mureș' },
			{ name: 'Neamț' },
			{ name: 'Olt' },
			{ name: 'Prahova' },
			{ name: 'Sălaj' },
			{ name: 'Satu Mare' },
			{ name: 'Sibiu' },
			{ name: 'Suceava' },
			{ name: 'Teleorman' },
			{ name: 'Timiș' },
			{ name: 'Tulcea' },
			{ name: 'Vâlcea' },
			{ name: 'Vaslui' },
			{ name: 'Vrancea' },
		],
	},
	{
		name: 'Russia',
		subregions: [
			{ name: 'Altai Krai' },
			{ name: 'Amur Oblast' },
			{ name: 'Arkhangelsk Oblast' },
			{ name: 'Astrakhan Oblast' },
			{ name: 'Autonomous Republic of Crimea' },
			{ name: 'Bashkortostan' },
			{ name: 'Belgorod Oblast' },
			{ name: 'Bryansk Oblast' },
			{ name: 'Buryatia' },
			{ name: 'Chechen Republic' },
			{ name: 'Chelyabinsk Oblast' },
			{ name: 'Chukotka Autonomous Okrug' },
			{ name: 'Chuvashia' },
			{ name: 'Ingushetia' },
			{ name: 'Irkutsk Oblast' },
			{ name: 'Ivanovo Oblast' },
			{ name: 'Jewish Autonomous Oblast' },
			{ name: 'Kabardino-Balkaria' },
			{ name: 'Kaliningrad' },
			{ name: 'Kaluga Oblast' },
			{ name: 'Kamchatka Krai' },
			{ name: 'Karachay-Cherkessia' },
			{ name: 'Kemerovo Oblast' },
			{ name: 'Khabarovsk Krai' },
			{ name: 'Khanty-Mansiysk Autonomous Okrug – Ugra' },
			{ name: 'Kirov Oblast' },
			{ name: 'Komi Republic' },
			{ name: 'Kostroma Oblast' },
			{ name: 'Krasnodar Krai' },
			{ name: 'Krasnoyarsk Krai' },
			{ name: 'Kursk Oblast' },
			{ name: 'Leningrad oblast' },
			{ name: 'Lipetsk Oblast' },
			{ name: 'Magadan Oblast' },
			{ name: 'Mari El' },
			{ name: 'Moscow' },
			{ name: 'Moscow Oblast' },
			{ name: 'Murmansk Oblast' },
			{ name: 'Nenets Autonomous Okrug' },
			{ name: 'Nizhny Novgorod Oblast' },
			{ name: 'Novgorod Oblast' },
			{ name: 'Novosibirsk Oblast' },
			{ name: 'Omsk Oblast' },
			{ name: 'Orenburg Oblast' },
			{ name: 'Oryol Oblast' },
			{ name: 'Penza Oblast' },
			{ name: 'Perm Krai' },
			{ name: 'Primorsky Krai' },
			{ name: 'Pskov Oblast' },
			{ name: 'Republic of Adygea' },
			{ name: 'Republic of Crimea' },
			{ name: 'Republic of Dagestan' },
			{ name: 'Republic of Kalmykia' },
			{ name: 'Republic of Karelia' },
			{ name: 'Republic of Khakassia' },
			{ name: 'Republic of Mordovia' },
			{ name: 'Republic of North Ossetia-Alania' },
			{ name: 'Rostov Oblast' },
			{ name: 'Ryazan Oblast' },
			{ name: 'Saint Petersburg' },
			{ name: 'Sakha Republic' },
			{ name: 'Sakhalin Oblast' },
			{ name: 'Samara Oblast' },
			{ name: 'Saratov Oblast' },
			{ name: 'Sevastopol' },
			{ name: 'Smolensk Oblast' },
			{ name: 'Stavropol Krai' },
			{ name: 'Sverdlovsk Oblast' },
			{ name: 'Tambov Oblast' },
			{ name: 'Tatarstan' },
			{ name: 'Tomsk Oblast' },
			{ name: 'Tula Oblast' },
			{ name: 'Tuva Republic' },
			{ name: 'Tver Oblast' },
			{ name: 'Tyumen Oblast' },
			{ name: 'Udmurtia' },
			{ name: 'Ulyanovsk Oblast' },
			{ name: 'Vladimir Oblast' },
			{ name: 'Volgograd Oblast' },
			{ name: 'Vologda Oblast' },
			{ name: 'Voronezh Oblast' },
			{ name: 'Yamalo-Nenets Autonomous Okrug' },
			{ name: 'Yaroslavl Oblast' },
			{ name: 'Zabaykalsky Krai' },
		],
	},
	{
		name: 'Rwanda',
		subregions: [
			{ name: 'East Province' },
			{ name: 'Kigali City' },
			{ name: 'Northern Province' },
			{ name: 'Southern Province' },
			{ name: 'Western Province' },
		],
	},
	{
		name: 'Saint Helena, Ascension and Tristan da Cunha',
		subregions: [{ name: 'Inaccessible Island' }, { name: 'Nightingale Island' }, { name: 'Tristan da Cunha' }],
	},
	{ name: 'Saint Kitts and Nevis', subregions: [{ name: 'Nevis' }, { name: 'Saint Kitts' }] },
	{
		name: 'Saint Lucia',
		subregions: [
			{ name: 'Anse la Raye' },
			{ name: 'Canaries' },
			{ name: 'Castries' },
			{ name: 'Choiseul' },
			{ name: 'Dennery' },
			{ name: 'Gros Islet' },
			{ name: 'Laborie' },
			{ name: 'Micoud' },
			{ name: 'Soufriere' },
			{ name: 'Vieux Fort' },
		],
	},
	{
		name: 'Saudi Arabia',
		subregions: [
			{ name: "'Asir Region" },
			{ name: 'Al Bahah Region' },
			{ name: 'Al Jawf Region' },
			{ name: 'Al Madinah Region' },
			{ name: 'Al-Qassim Region' },
			{ name: 'Eastern Region' },
			{ name: 'Hayel Region' },
			{ name: 'Jazan Region' },
			{ name: 'Makkah Region' },
			{ name: 'Najran Region' },
			{ name: 'Northern Borders Region' },
			{ name: 'Riyadh Region' },
			{ name: 'Tabuk Region' },
		],
	},
	{ name: 'Serbia', subregions: [{ name: 'Central Serbia' }, { name: 'Vojvodina' }] },
	{
		name: 'Sierra Leone',
		subregions: [
			{ name: 'Eastern Province' },
			{ name: 'North Western Province' },
			{ name: 'Northern Province' },
			{ name: 'Southern Province' },
			{ name: 'Western Area' },
		],
	},
	{
		name: 'Slovakia',
		subregions: [
			{ name: 'Region of Banská Bystrica' },
			{ name: 'Region of Bratislava' },
			{ name: 'Region of Košice' },
			{ name: 'Region of Nitra' },
			{ name: 'Region of Prešov' },
			{ name: 'Region of Trenčín' },
			{ name: 'Region of Trnava' },
			{ name: 'Region of Žilina' },
		],
	},
	{
		name: 'Solomon Islands',
		subregions: [
			{ name: 'Central Province' },
			{ name: 'Choiseul' },
			{ name: 'Guadalcanal' },
			{ name: 'Honiara' },
			{ name: 'Isabel' },
			{ name: 'Makira-Ulawa' },
			{ name: 'Malaita' },
			{ name: 'Rennell and Bellona' },
			{ name: 'Temotu' },
			{ name: 'Western' },
		],
	},
	{
		name: 'Somalia',
		subregions: [
			{ name: 'Awdal' },
			{ name: 'Bakool' },
			{ name: 'Banaadir' },
			{ name: 'Bari' },
			{ name: 'Bay' },
			{ name: 'Galgaduud' },
			{ name: 'Gedo' },
			{ name: 'Hiiraan' },
			{ name: 'Lower Juba' },
			{ name: 'Lower Shabelle' },
			{ name: 'Middle Juba' },
			{ name: 'Middle Shebelle' },
			{ name: 'Mudug' },
			{ name: 'Nugaal' },
			{ name: 'Sanaag' },
			{ name: 'Sool' },
			{ name: 'Togdheer' },
			{ name: 'Woqooyi Galbeed' },
		],
	},
	{
		name: 'South Africa',
		subregions: [
			{ name: 'Eastern Cape' },
			{ name: 'Free State' },
			{ name: 'Gauteng' },
			{ name: 'KwaZulu-Natal' },
			{ name: 'Limpopo' },
			{ name: 'Mpumalanga' },
			{ name: 'North West' },
			{ name: 'Northern Cape' },
			{ name: 'Western Cape' },
		],
	},
	{
		name: 'South Korea',
		subregions: [
			{ name: 'Busan' },
			{ name: 'Chungcheongbuk-do' },
			{ name: 'Chungcheongnam-do' },
			{ name: 'Daegu' },
			{ name: 'Daejeon' },
			{ name: 'Gwangju' },
			{ name: 'Gyeonggi-do' },
			{ name: 'Gyeongsangbuk-do' },
			{ name: 'Gyeongsangnam-do' },
			{ name: 'Incheon' },
			{ name: 'Jeju-do' },
			{ name: 'Jeollabuk-do' },
			{ name: 'Jeollanam-do' },
			{ name: 'Sejong' },
			{ name: 'Seoul' },
			{ name: 'Ulsan' },
		],
	},
	{
		name: 'South Sudan',
		subregions: [
			{ name: 'Central Equatoria' },
			{ name: 'Eastern Equatoria' },
			{ name: 'Jonglei' },
			{ name: 'Lakes' },
			{ name: 'Northern Bahr el Ghazal' },
			{ name: 'Unity' },
			{ name: 'Upper Nile' },
			{ name: 'Warrap' },
			{ name: 'Western Bahr el Ghazal' },
			{ name: 'Western Equatoria' },
		],
	},
	{
		name: 'Spain',
		subregions: [
			{ name: 'Andalusia' },
			{ name: 'Aragon' },
			{ name: 'Asturias' },
			{ name: 'Autonomous Community of the Basque Country' },
			{ name: 'Balearic Islands' },
			{ name: 'Canary Islands' },
			{ name: 'Cantabria' },
			{ name: 'Castile and León' },
			{ name: 'Castile-La Mancha' },
			{ name: 'Catalonia' },
			{ name: 'Ceuta' },
			{ name: 'Community of Madrid' },
			{ name: 'Extremadura' },
			{ name: 'Galicia' },
			{ name: 'Melilla' },
			{ name: 'Navarre' },
			{ name: 'Plazas de Soberanía' },
			{ name: 'Region of Murcia' },
			{ name: 'Rioja' },
			{ name: 'Valencian Community' },
		],
	},
	{
		name: 'Sri Lanka',
		subregions: [
			{ name: 'Central Province' },
			{ name: 'Eastern Province' },
			{ name: 'North Central Province' },
			{ name: 'North Western Province' },
			{ name: 'Northern Province' },
			{ name: 'Sabaragamuwa Province' },
			{ name: 'Southern Province' },
			{ name: 'Uva Province' },
			{ name: 'Western Province' },
		],
	},
	{
		name: 'Sudan',
		subregions: [
			{ name: 'Blue Nile State' },
			{ name: 'Central Darfur' },
			{ name: 'East Darfur State' },
			{ name: 'Gedarif State' },
			{ name: 'Gezira State' },
			{ name: 'Kassala' },
			{ name: 'Khartoum State' },
			{ name: 'North Darfur State' },
			{ name: 'North Kordofan State' },
			{ name: 'Northern State' },
			{ name: 'Red Sea State' },
			{ name: 'River Nile' },
			{ name: 'Sennar State' },
			{ name: 'South Darfur State' },
			{ name: 'South Kordofan State' },
			{ name: 'West Darfur State' },
			{ name: 'West Kurdufan' },
			{ name: 'White Nile State' },
		],
	},
	{
		name: 'Suriname',
		subregions: [
			{ name: 'Brokopondo' },
			{ name: 'Commewijne' },
			{ name: 'Coronie' },
			{ name: 'Marowijne' },
			{ name: 'Nickerie' },
			{ name: 'Para' },
			{ name: 'Paramaribo' },
			{ name: 'Saramacca' },
			{ name: 'Sipaliwini' },
			{ name: 'Wanica' },
		],
	},
	{
		name: 'Sweden',
		subregions: [
			{ name: 'Blekinge County' },
			{ name: 'Dalecarlia' },
			{ name: 'Gävleborg County' },
			{ name: 'Gotland County' },
			{ name: 'Halland County' },
			{ name: 'Jämtland County' },
			{ name: 'Jönköping County' },
			{ name: 'Kalmar County' },
			{ name: 'Kronoberg County' },
			{ name: 'Norrbotten County' },
			{ name: 'Örebro County' },
			{ name: 'Östergötland County' },
			{ name: 'Skåne County' },
			{ name: 'Södermanland County' },
			{ name: 'Stockholm County' },
			{ name: 'Uppsala County' },
			{ name: 'Värmland County' },
			{ name: 'Västerbotten County' },
			{ name: 'Västernorrland County' },
			{ name: 'Västmanland County' },
			{ name: 'Västra Götaland County' },
		],
	},
	{
		name: 'Switzerland',
		subregions: [
			{ name: 'Aargau' },
			{ name: 'Appenzell Ausserrhoden' },
			{ name: 'Appenzell Innerrhoden' },
			{ name: 'Basel-City' },
			{ name: 'Basel-Landschaft' },
			{ name: 'Bern' },
			{ name: 'Fribourg' },
			{ name: 'Geneva' },
			{ name: 'Glarus' },
			{ name: 'Grisons' },
			{ name: 'Jura' },
			{ name: 'Luzern' },
			{ name: 'Neuchâtel' },
			{ name: 'Nidwalden' },
			{ name: 'Obwalden' },
			{ name: 'Sankt Gallen' },
			{ name: 'Schaffhausen' },
			{ name: 'Schwyz' },
			{ name: 'Solothurn' },
			{ name: 'Thurgau' },
			{ name: 'Ticino' },
			{ name: 'Uri' },
			{ name: 'Valais/Wallis' },
			{ name: 'Vaud' },
			{ name: 'Zug' },
			{ name: 'Zurich' },
		],
	},
	{
		name: 'Syria',
		subregions: [
			{ name: 'Al-Hasaka Governorate' },
			{ name: 'Al-Qunaitra Governorate' },
			{ name: 'Aleppo Governorate' },
			{ name: 'Ar-Raqqah Governorate' },
			{ name: 'As-Suwayda Governorate' },
			{ name: 'Damascus Governorate' },
			{ name: 'Daraa Governorate' },
			{ name: 'Deir Ezzor Governorate' },
			{ name: 'Hama Governorate' },
			{ name: 'Homs Governorate' },
			{ name: 'Idlib Governorate' },
			{ name: 'Latakia Governorate' },
			{ name: 'Rif Dimashq Governorate' },
			{ name: 'Tartus Governorate' },
		],
	},
	{ name: 'São Tomé and Príncipe', subregions: [{ name: 'Príncipe Province' }, { name: 'São Tomé Province' }] },
	{
		name: 'Taiwan',
		subregions: [
			{ name: 'Fujian Province' },
			{ name: 'Kaohsiung' },
			{ name: 'New Taipei' },
			{ name: 'Taichung' },
			{ name: 'Tainan' },
			{ name: 'Taipei' },
			{ name: 'Taiwan Province' },
			{ name: 'Taoyuan City' },
		],
	},
	{
		name: 'Tajikistan',
		subregions: [
			{ name: 'Districts of Republican Subordination' },
			{ name: 'Dushanbe' },
			{ name: 'Gorno-Badakhshan Autonomous Region' },
			{ name: 'Khatlon Region' },
			{ name: 'Sughd Region' },
		],
	},
	{
		name: 'Tanzania',
		subregions: [
			{ name: 'Arusha' },
			{ name: 'Dar es Salaam' },
			{ name: 'Dodoma' },
			{ name: 'Geita' },
			{ name: 'Iringa' },
			{ name: 'Kagera' },
			{ name: 'Katavi' },
			{ name: 'Kigoma' },
			{ name: 'Kilimanjaro' },
			{ name: 'Lindi' },
			{ name: 'Manyara' },
			{ name: 'Mara' },
			{ name: 'Mbeya' },
			{ name: 'Morogoro' },
			{ name: 'Mtwara' },
			{ name: 'Mwanza' },
			{ name: 'Njombe' },
			{ name: 'North Pemba' },
			{ name: 'Pwani' },
			{ name: 'Rukwa' },
			{ name: 'Ruvuma' },
			{ name: 'Shinyanga' },
			{ name: 'Simiyu' },
			{ name: 'Singida' },
			{ name: 'South Pemba' },
			{ name: 'Tabora' },
			{ name: 'Tanga' },
			{ name: 'Zanzibar North' },
			{ name: 'Zanzibar South & Central' },
			{ name: 'Zanzibar Urban/West' },
		],
	},
	{
		name: 'Thailand',
		subregions: [
			{ name: 'Amnat Charoen Province' },
			{ name: 'Ang Thong Province' },
			{ name: 'Bangkok' },
			{ name: 'Bueng Kan Province' },
			{ name: 'Buri Ram Province' },
			{ name: 'Chachoengsao Province' },
			{ name: 'Chai Nat Province' },
			{ name: 'Chaiyaphum Province' },
			{ name: 'Chanthaburi Province' },
			{ name: 'Chiang Mai Province' },
			{ name: 'Chiang Rai Province' },
			{ name: 'Chon Buri Province' },
			{ name: 'Chumphon Province' },
			{ name: 'Kalasin' },
			{ name: 'Kamphaeng Phet Province' },
			{ name: 'Kanchanaburi Province' },
			{ name: 'Khon Kaen Province' },
			{ name: 'Krabi Province' },
			{ name: 'Lampang Province' },
			{ name: 'Lamphun Province' },
			{ name: 'Loei Province' },
			{ name: 'Lop Buri Province' },
			{ name: 'Mae Hong Son Province' },
			{ name: 'Maha Sarakham Province' },
			{ name: 'Mukdahan Province' },
			{ name: 'Nakhon Nayok Province' },
			{ name: 'Nakhon Pathom Province' },
			{ name: 'Nakhon Phanom Province' },
			{ name: 'Nakhon Ratchasima Province' },
			{ name: 'Nakhon Sawan Province' },
			{ name: 'Nakhon Si Thammarat Province' },
			{ name: 'Nan Province' },
			{ name: 'Narathiwat Province' },
			{ name: 'Nong Bua Lam Phu Province' },
			{ name: 'Nong Khai Province' },
			{ name: 'Nonthaburi Province' },
			{ name: 'Pathum Thani Province' },
			{ name: 'Pattani Province' },
			{ name: 'Phang-nga Province' },
			{ name: 'Phatthalung Province' },
			{ name: 'Phayao Province' },
			{ name: 'Phetchabun Province' },
			{ name: 'Phetchaburi Province' },
			{ name: 'Phichit Province' },
			{ name: 'Phitsanulok Province' },
			{ name: 'Phra Nakhon Si Ayutthaya Province' },
			{ name: 'Phrae Province' },
			{ name: 'Phuket Province' },
			{ name: 'Prachin Buri Province' },
			{ name: 'Prachuap Khiri Khan Province' },
			{ name: 'Ranong Province' },
			{ name: 'Ratchaburi Province' },
			{ name: 'Rayong Province' },
			{ name: 'Roi Et Province' },
			{ name: 'Sa Kaeo Province' },
			{ name: 'Sakon Nakhon Province' },
			{ name: 'Samut Prakan Province' },
			{ name: 'Samut Sakhon Province' },
			{ name: 'Samut Songkhram Province' },
			{ name: 'Saraburi Province' },
			{ name: 'Satun Province' },
			{ name: 'Si Sa Ket Province' },
			{ name: 'Sing Buri Province' },
			{ name: 'Songkhla Province' },
			{ name: 'Sukhothai Province' },
			{ name: 'Suphan Buri Province' },
			{ name: 'Surat Thani Province' },
			{ name: 'Surin Province' },
			{ name: 'Tak Province' },
			{ name: 'Trang Province' },
			{ name: 'Trat Province' },
			{ name: 'Ubon Ratchathani Province' },
			{ name: 'Udon Thani Province' },
			{ name: 'Uthai Thani Province' },
			{ name: 'Uttaradit Province' },
			{ name: 'Yala Province' },
			{ name: 'Yasothon Province' },
		],
	},
	{
		name: 'The Gambia',
		subregions: [
			{ name: 'Banjul City Council' },
			{ name: 'Central River' },
			{ name: 'Kanifing Municipal Council' },
			{ name: 'Lower River' },
			{ name: 'North Bank' },
			{ name: 'Upper River' },
			{ name: 'West Coast' },
		],
	},
	{
		name: 'Togo',
		subregions: [
			{ name: 'Centrale Region' },
			{ name: 'Kara Region' },
			{ name: 'Lomé' },
			{ name: 'Maritime Region' },
			{ name: 'Plateaux Region' },
			{ name: 'Savanes Region' },
		],
	},
	{
		name: 'Tonga',
		subregions: [
			{ name: 'Haʻapai' },
			{ name: 'ʻEua' },
			{ name: 'Ongo Niua' },
			{ name: 'Tongatapu' },
			{ name: 'Vavaʻu' },
		],
	},
	{
		name: 'Trinidad and Tobago',
		subregions: [
			{ name: 'Chaguanas' },
			{ name: 'Couva-Tabaquite-Talparo' },
			{ name: 'Diego Martin' },
			{ name: 'Penal-Debe' },
			{ name: 'Point Fortin' },
			{ name: 'Princes Town' },
			{ name: 'Rio Claro-Mayaro' },
			{ name: 'San Fernando' },
			{ name: 'Siparia' },
			{ name: 'Tobago' },
		],
	},
	{
		name: 'Tunisia',
		subregions: [
			{ name: 'Al Kaf' },
			{ name: 'Ariana' },
			{ name: 'Béja' },
			{ name: 'Ben Arous' },
			{ name: 'Bizerte' },
			{ name: 'Gabès' },
			{ name: 'Gafsa' },
			{ name: 'Jendouba' },
			{ name: 'Kairouan' },
			{ name: 'Kasserine' },
			{ name: 'Kébili' },
			{ name: 'Mahdia' },
			{ name: 'Manouba' },
			{ name: 'Médenine' },
			{ name: 'Monastir' },
			{ name: 'Nabeul' },
			{ name: 'Sfax' },
			{ name: 'Sidi Bouzid' },
			{ name: 'Siliana' },
			{ name: 'Sousse' },
			{ name: 'Tataouine' },
			{ name: 'Tozeur' },
			{ name: 'Tunis' },
			{ name: 'Zaghouan Governorate' },
		],
	},
	{
		name: 'Turkey',
		subregions: [
			{ name: 'Adana' },
			{ name: 'Adıyaman' },
			{ name: 'Afyonkarahisar' },
			{ name: 'Ağrı' },
			{ name: 'Aksaray' },
			{ name: 'Amasya' },
			{ name: 'Ankara' },
			{ name: 'Antalya' },
			{ name: 'Ardahan' },
			{ name: 'Artvin' },
			{ name: 'Aydın' },
			{ name: 'Balıkesir' },
			{ name: 'Bartın' },
			{ name: 'Batman' },
			{ name: 'Bayburt' },
			{ name: 'Bilecik' },
			{ name: 'Bingöl' },
			{ name: 'Bitlis' },
			{ name: 'Bolu' },
			{ name: 'Burdur' },
			{ name: 'Bursa' },
			{ name: 'Canakkale' },
			{ name: 'Çankırı' },
			{ name: 'Çorum' },
			{ name: 'Denizli' },
			{ name: 'Diyarbakır' },
			{ name: 'Düzce' },
			{ name: 'Edirne' },
			{ name: 'Elazığ' },
			{ name: 'Erzincan' },
			{ name: 'Erzurum' },
			{ name: 'Eskişehir' },
			{ name: 'Gaziantep' },
			{ name: 'Giresun' },
			{ name: 'Gümüşhane' },
			{ name: 'Hakkâri' },
			{ name: 'Hatay' },
			{ name: 'Iğdır' },
			{ name: 'Isparta' },
			{ name: 'Istanbul' },
			{ name: 'Izmir' },
			{ name: 'Kahramanmaraş' },
			{ name: 'Karabük' },
			{ name: 'Karaman' },
			{ name: 'Kars' },
			{ name: 'Kastamonu' },
			{ name: 'Kayseri' },
			{ name: 'Kilis' },
			{ name: 'Kırıkkale' },
			{ name: 'Kırklareli' },
			{ name: 'Kırşehir' },
			{ name: 'Kocaeli' },
			{ name: 'Konya' },
			{ name: 'Kütahya' },
			{ name: 'Malatya' },
			{ name: 'Manisa' },
			{ name: 'Mardin' },
			{ name: 'Mersin' },
			{ name: 'Muğla' },
			{ name: 'Muş' },
			{ name: 'Nevşehir' },
			{ name: 'Niğde' },
			{ name: 'Ordu' },
			{ name: 'Osmaniye' },
			{ name: 'Rize' },
			{ name: 'Sakarya' },
			{ name: 'Samsun' },
			{ name: 'Şanlıurfa' },
			{ name: 'Siirt' },
			{ name: 'Sinop' },
			{ name: 'Sivas' },
			{ name: 'Şırnak' },
			{ name: 'Tekirdağ' },
			{ name: 'Tokat' },
			{ name: 'Trabzon' },
			{ name: 'Tunceli' },
			{ name: 'Uşak' },
			{ name: 'Van' },
			{ name: 'Yalova' },
			{ name: 'Yozgat' },
			{ name: 'Zonguldak' },
		],
	},
	{
		name: 'Turkmenistan',
		subregions: [
			{ name: 'Ahal Region' },
			{ name: 'Ashgabat' },
			{ name: 'Balkan Region' },
			{ name: 'Daşoguz Region' },
			{ name: 'Lebap Region' },
			{ name: 'Mary Region' },
		],
	},
	{
		name: 'Uganda',
		subregions: [
			{ name: 'Abim' },
			{ name: 'Adjumani' },
			{ name: 'Agago' },
			{ name: 'Alebtong' },
			{ name: 'Amolatar' },
			{ name: 'Amudat' },
			{ name: 'Amuria' },
			{ name: 'Amuru' },
			{ name: 'Apac' },
			{ name: 'Arua' },
			{ name: 'Budaka' },
			{ name: 'Bududa' },
			{ name: 'Bugiri' },
			{ name: 'Buhweju' },
			{ name: 'Buikwe' },
			{ name: 'Bukedea' },
			{ name: 'Bukomansimbi' },
			{ name: 'Bukwo' },
			{ name: 'Bulambuli' },
			{ name: 'Buliisa' },
			{ name: 'Bundibugyo' },
			{ name: 'Bushenyi' },
			{ name: 'Busia' },
			{ name: 'Butaleja' },
			{ name: 'Butambala' },
			{ name: 'Buvuma' },
			{ name: 'Buyende' },
			{ name: 'Dokolo' },
			{ name: 'Gomba' },
			{ name: 'Gulu' },
			{ name: 'Hoima' },
			{ name: 'Ibanda' },
			{ name: 'Iganga' },
			{ name: 'Isingiro' },
			{ name: 'Jinja' },
			{ name: 'Kaabong' },
			{ name: 'Kabale' },
			{ name: 'Kabarole' },
			{ name: 'Kaberamaido' },
			{ name: 'Kalangala' },
			{ name: 'Kaliro' },
			{ name: 'Kalungu' },
			{ name: 'Kampala' },
			{ name: 'Kamuli' },
			{ name: 'Kamwenge' },
			{ name: 'Kanungu' },
			{ name: 'Kapchorwa' },
			{ name: 'Kasese' },
			{ name: 'Katakwi' },
			{ name: 'Kayunga' },
			{ name: 'Kibaale' },
			{ name: 'Kiboga' },
			{ name: 'Kibuku' },
			{ name: 'Kiryandongo' },
			{ name: 'Kisoro' },
			{ name: 'Kitgum' },
			{ name: 'Koboko' },
			{ name: 'Kole' },
			{ name: 'Kotido' },
			{ name: 'Kumi' },
			{ name: 'Kween' },
			{ name: 'Kyankwanzi' },
			{ name: 'Lamwo' },
			{ name: 'Lira District' },
			{ name: 'Luuka' },
			{ name: 'Luweero' },
			{ name: 'Lyantonde' },
			{ name: 'Manafwa' },
			{ name: 'Maracha' },
			{ name: 'Masaka' },
			{ name: 'Masindi' },
			{ name: 'Mayuge' },
			{ name: 'Mbale' },
			{ name: 'Mbarara' },
			{ name: 'Mitooma' },
			{ name: 'Mityana' },
			{ name: 'Moroto' },
			{ name: 'Moyo' },
			{ name: 'Mpigi' },
			{ name: 'Mubende' },
			{ name: 'Mukono' },
			{ name: 'Nakapiripirit' },
			{ name: 'Nakaseke' },
			{ name: 'Nakasongola' },
			{ name: 'Namayingo' },
			{ name: 'Namutumba' },
			{ name: 'Napak' },
			{ name: 'Nebbi' },
			{ name: 'Ngora' },
			{ name: 'Ntoroko' },
			{ name: 'Ntungamo' },
			{ name: 'Nwoya' },
			{ name: 'Otuke' },
			{ name: 'Oyam' },
			{ name: 'Pader' },
			{ name: 'Pallisa' },
			{ name: 'Rubirizi' },
			{ name: 'Rukungiri' },
			{ name: 'Sembabule' },
			{ name: 'Serere' },
			{ name: 'Sheema' },
			{ name: 'Sironko' },
			{ name: 'Soroti' },
			{ name: 'Tororo' },
			{ name: 'Wakiso' },
			{ name: 'Yumbe' },
			{ name: 'Zombo' },
		],
	},
	{
		name: 'Ukraine',
		subregions: [
			{ name: 'Autonomous Republic of Crimea' },
			{ name: 'Cherkasy Oblast' },
			{ name: 'Chernihiv Oblast' },
			{ name: 'Chernivtsi Oblast' },
			{ name: 'Dnipropetrovsk Oblast' },
			{ name: 'Donetsk Oblast' },
			{ name: 'Ivano-Frankivsk Oblast' },
			{ name: 'Kharkiv Oblast' },
			{ name: 'Kherson Oblast' },
			{ name: 'Khmelnytskyi Oblast' },
			{ name: 'Kirovohrad Oblast' },
			{ name: 'Kyiv' },
			{ name: 'Kyiv Oblast' },
			{ name: 'Luhansk Oblast' },
			{ name: 'Lviv Oblast' },
			{ name: 'Mykolaiv Oblast' },
			{ name: 'Odesa Oblast' },
			{ name: 'Poltava Oblast' },
			{ name: 'Republic of Crimea' },
			{ name: 'Rivne Oblast' },
			{ name: 'Sevastopol' },
			{ name: 'Sumy Oblast' },
			{ name: 'Ternopil Oblast' },
			{ name: 'Vinnytsia Oblast' },
			{ name: 'Volyn Oblast' },
			{ name: 'Zakarpattia Oblast' },
			{ name: 'Zaporizhia Oblast' },
			{ name: 'Zhytomyr Oblast' },
			{ name: 'Київська міська громада' },
		],
	},
	{
		name: 'United Arab Emirates',
		subregions: [
			{ name: 'Abu Dhabi Emirate' },
			{ name: 'Ajman Emirate' },
			{ name: 'Dubai' },
			{ name: 'Fujairah Emirate' },
			{ name: 'Ras al-Khaimah' },
			{ name: 'Sharjah Emirate' },
			{ name: 'Umm al-Quwain' },
		],
	},
	{
		name: 'United Kingdom',
		subregions: [{ name: 'England' }, { name: 'Northern Ireland' }, { name: 'Scotland' }, { name: 'Wales' }],
	},
	{
		name: 'United States',
		subregions: [
			{ name: 'Alabama' },
			{ name: 'Alaska' },
			{ name: 'American Samoa' },
			{ name: 'Arizona' },
			{ name: 'Arkansas' },
			{ name: 'California' },
			{ name: 'Colorado' },
			{ name: 'Connecticut' },
			{ name: 'Delaware' },
			{ name: 'Florida' },
			{ name: 'Georgia' },
			{ name: 'Grand Traverse Reservation' },
			{ name: 'Guam' },
			{ name: 'Hawaii' },
			{ name: 'Idaho' },
			{ name: 'Île de la Navasse / Navassa Island' },
			{ name: 'Illinois' },
			{ name: 'Indiana' },
			{ name: 'Iowa' },
			{ name: 'Kansas' },
			{ name: 'Kentucky' },
			{ name: 'Little Traverse Bay Band of Odawa Reservation' },
			{ name: 'Little Traverse Bay Band of Odawas' },
			{ name: 'Little Traverse Bay Band of Odawas Reservation' },
			{ name: 'Little Traverse Bay Bands Of Odawa Reservation' },
			{ name: 'Little Traverse Bay Bands of Odawas Reservation' },
			{ name: 'Louisiana' },
			{ name: 'Maine' },
			{ name: 'Maryland' },
			{ name: 'Massachusetts' },
			{ name: 'Michigan' },
			{ name: 'Minnesota' },
			{ name: 'Mississippi' },
			{ name: 'Missouri' },
			{ name: 'Montana' },
			{ name: 'Nebraska' },
			{ name: 'Nevada' },
			{ name: 'New Hampshire' },
			{ name: 'New Jersey' },
			{ name: 'New Mexico' },
			{ name: 'New York' },
			{ name: 'North Carolina' },
			{ name: 'North Dakota' },
			{ name: 'Northern Mariana Islands' },
			{ name: 'Ohio' },
			{ name: 'Oklahoma' },
			{ name: 'Oregon' },
			{ name: 'Pennsylvania' },
			{ name: 'Puerto Rico' },
			{ name: 'Puyallup Tribe' },
			{ name: 'Puyallup Tribe Reservation' },
			{ name: 'Rhode Island' },
			{ name: 'South Carolina' },
			{ name: 'South Dakota' },
			{ name: 'Tennessee' },
			{ name: 'Texas' },
			{ name: 'United States Virgin Islands' },
			{ name: 'Utah' },
			{ name: 'Vermont' },
			{ name: 'Virginia' },
			{ name: 'Washington' },
			{ name: 'Washington, D.C.' },
			{ name: 'West Virginia' },
			{ name: 'Wisconsin' },
			{ name: 'Wyoming' },
		],
	},
	{
		name: 'Uruguay',
		subregions: [
			{ name: 'Artigas' },
			{ name: 'Canelones' },
			{ name: 'Cerro Largo' },
			{ name: 'Colonia' },
			{ name: 'Durazno' },
			{ name: 'Flores' },
			{ name: 'Florida' },
			{ name: 'Lavalleja' },
			{ name: 'Maldonado' },
			{ name: 'Montevideo' },
			{ name: 'Paysandú' },
			{ name: 'Río Negro' },
			{ name: 'Rivera' },
			{ name: 'Rocha' },
			{ name: 'Salto' },
			{ name: 'San José' },
			{ name: 'Soriano' },
			{ name: 'Tacuarembó' },
			{ name: 'Treinta y Tres' },
		],
	},
	{
		name: 'Uzbekistan',
		subregions: [
			{ name: 'Andijan Region' },
			{ name: 'Bukhara Region' },
			{ name: 'Fergana Region' },
			{ name: 'Jizzakh Region' },
			{ name: 'Namangan Region' },
			{ name: 'Navoiy Region' },
			{ name: 'Qashqadaryo Region' },
			{ name: 'Republic of Karakalpakstan' },
			{ name: 'Samarqand Region' },
			{ name: 'Sirdaryo Region' },
			{ name: 'Surxondaryo Region' },
			{ name: 'Tashkent' },
			{ name: 'Tashkent Region' },
			{ name: 'Xorazm Region' },
		],
	},
	{
		name: 'Vanuatu',
		subregions: [
			{ name: 'Malampa' },
			{ name: 'Penama' },
			{ name: 'Sanma' },
			{ name: 'Shefa Province' },
			{ name: 'Tafea' },
			{ name: 'Torba' },
		],
	},
	{
		name: 'Venezuela',
		subregions: [
			{ name: 'Amazonas State' },
			{ name: 'Anzoategui State' },
			{ name: 'Apure State' },
			{ name: 'Aragua' },
			{ name: 'Barinas' },
			{ name: 'Bolivar State' },
			{ name: 'Carabobo' },
			{ name: 'Cojedes' },
			{ name: 'Delta Amacuro State' },
			{ name: 'Distrito Capital' },
			{ name: 'Falcón' },
			{ name: 'Federal Dependencies' },
			{ name: 'Guarico State' },
			{ name: 'La Guaira' },
			{ name: 'Lara' },
			{ name: 'Mérida' },
			{ name: 'Miranda' },
			{ name: 'Monagas State' },
			{ name: 'Nueva Esparta' },
			{ name: 'Portuguesa State' },
			{ name: 'Sucre' },
			{ name: 'Táchira' },
			{ name: 'Trujillo' },
			{ name: 'Yaracuy' },
			{ name: 'Zulia' },
		],
	},
	{
		name: 'Vietnam',
		subregions: [
			{ name: 'Ba Ria-Vung Tau Province' },
			{ name: 'Bac Giang Province' },
			{ name: 'Bac Kan Province' },
			{ name: 'Bac Lieu province' },
			{ name: 'Bac Ninh province' },
			{ name: 'Bến Tre Province' },
			{ name: 'Bình Định Province' },
			{ name: 'Binh Duong province' },
			{ name: 'Bình Phước Province' },
			{ name: 'Binh Thuan province' },
			{ name: 'Ca Mau province' },
			{ name: 'Can Tho City' },
			{ name: 'Cao Bang province' },
			{ name: 'Da Nang' },
			{ name: 'Đắk Lắk province' },
			{ name: 'Đắk Nông Province' },
			{ name: 'Điện Biên Province' },
			{ name: 'Dong Nai province' },
			{ name: 'Dong Thap Province' },
			{ name: 'Gia Lai Province' },
			{ name: 'Hà Giang Province' },
			{ name: 'Ha Nam province' },
			{ name: 'Ha Tinh Province' },
			{ name: 'Hải Dương Province' },
			{ name: 'Haiphong' },
			{ name: 'Hanoi' },
			{ name: 'Hậu Giang Province' },
			{ name: 'Ho Chi Minh City' },
			{ name: 'Hoà Bình province' },
			{ name: 'Hung Yen Province' },
			{ name: 'Kien Giang Province' },
			{ name: 'Kon Tum province' },
			{ name: 'Lai Chau province' },
			{ name: 'Lâm Đồng Province' },
			{ name: 'Lạng Sơn Province' },
			{ name: 'Lao Cai province' },
			{ name: 'Long An province' },
			{ name: 'Nam Dinh province' },
			{ name: 'Nghe An province' },
			{ name: 'Ninh Binh province' },
			{ name: 'Ninh Thuan province' },
			{ name: 'Phu Tho Province' },
			{ name: 'Phu Yen province' },
			{ name: 'Quang Binh province' },
			{ name: 'Quảng Ngãi' },
			{ name: 'Quang Ninh Province' },
			{ name: 'Quang Tri province' },
			{ name: 'Soc Trang province' },
			{ name: 'Son La province' },
			{ name: 'Tay Ninh province' },
			{ name: 'Thai Binh province' },
			{ name: 'Thai Nguyen province' },
			{ name: 'Thanh Hoa' },
			{ name: 'Thừa Thiên Huế Province' },
			{ name: 'Tien Giang province' },
			{ name: 'Tỉnh Quảng Nam' },
			{ name: 'Tra Vinh province' },
			{ name: 'Tuyen Quang Province' },
			{ name: 'Vinh Long province' },
			{ name: 'Vinh Phuc Province' },
			{ name: 'Yen Bai Province' },
		],
	},
	{
		name: 'Yemen',
		subregions: [
			{ name: 'Abyan Governorate' },
			{ name: "Ad Dali' Governorate" },
			{ name: 'Aden Governorate' },
			{ name: "Al Bayda' Governorate" },
			{ name: 'Al Hudaydah Governorate' },
			{ name: 'Al Jawf Governorate' },
			{ name: 'Al Mahrah Governorate' },
			{ name: 'Al Mahwit Governorate' },
			{ name: 'Amanat Al Asimah' },
			{ name: 'Amran Governorate' },
			{ name: 'Dhamar Governorate' },
			{ name: 'Hadramaut Governorate' },
			{ name: 'Hajjah Governorate' },
			{ name: 'Ibb Governorate' },
			{ name: 'Lahij Governorate' },
			{ name: 'Marib Governorate' },
			{ name: 'Raymah Governorate' },
			{ name: "Sa'dah Governorate" },
			{ name: "Sana'a Governorate" },
			{ name: 'Shabwah Governorate' },
			{ name: 'Socotra Governorate' },
			{ name: "Ta'izz Governorate" },
		],
	},
	{
		name: 'Zambia',
		subregions: [
			{ name: 'Central Province' },
			{ name: 'Copperbelt Province' },
			{ name: 'Eastern Province' },
			{ name: 'Luapula Province' },
			{ name: 'Lusaka Province' },
			{ name: 'Muchinga Province' },
			{ name: 'North-Western Province' },
			{ name: 'Northern Province' },
			{ name: 'Southern Province' },
			{ name: 'Western Province' },
		],
	},
	{
		name: 'Zimbabwe',
		subregions: [
			{ name: 'Bulawayo Province' },
			{ name: 'Harare Province' },
			{ name: 'Manicaland' },
			{ name: 'Mashonaland Central' },
			{ name: 'Mashonaland East' },
			{ name: 'Mashonaland West' },
			{ name: 'Masvingo' },
			{ name: 'Matabeleland North' },
			{ name: 'Matabeleland South' },
			{ name: 'Midlands' },
		],
	},
];
