export default {
	100: 'Bulgaria',
	104: 'Myanmar',
	108: 'Burundi',
	112: 'Belarus',
	116: 'Cambodia',
	120: 'Cameroon',
	124: 'Canada',
	132: 'Cape Verde',
	136: 'Cayman Islands',
	140: 'Central African Republic',
	144: 'Sri Lanka',
	148: 'Chad',
	152: 'Chile',
	156: 'China',
	158: 'Taiwan',
	162: 'Christmas Island',
	166: 'Cocos (Keeling) Islands',
	170: 'Colombia',
	174: 'Comoros',
	175: 'Mayotte',
	178: 'Republic of the Congo',
	180: 'DR Congo',
	184: 'Cook Islands',
	188: 'Costa Rica',
	191: 'Croatia',
	192: 'Cuba',
	196: 'Cyprus',
	203: 'Czech Republic',
	204: 'Benin',
	208: 'Denmark',
	212: 'Dominica',
	214: 'Dominican Republic',
	218: 'Ecuador',
	222: 'El Salvador',
	226: 'Equatorial Guinea',
	231: 'Ethiopia',
	232: 'Eritrea',
	233: 'Estonia',
	234: 'Faroe Islands',
	238: 'Falkland Islands',
	239: 'South Georgia',
	242: 'Fiji',
	246: 'Finland',
	248: 'Åland Islands',
	250: 'France',
	254: 'French Guiana',
	258: 'French Polynesia',
	260: 'French Southern and Antarctic Lands',
	262: 'Djibouti',
	266: 'Gabon',
	268: 'Georgia',
	270: 'Gambia',
	275: 'Palestine',
	276: 'Germany',
	288: 'Ghana',
	292: 'Gibraltar',
	296: 'Kiribati',
	300: 'Greece',
	304: 'Greenland',
	308: 'Grenada',
	312: 'Guadeloupe',
	316: 'Guam',
	320: 'Guatemala',
	324: 'Guinea',
	328: 'Guyana',
	332: 'Haiti',
	334: 'Heard Island and McDonald Islands',
	336: 'Vatican City',
	340: 'Honduras',
	344: 'Hong Kong',
	348: 'Hungary',
	352: 'Iceland',
	356: 'India',
	360: 'Indonesia',
	364: 'Iran',
	368: 'Iraq',
	372: 'Ireland',
	376: 'Israel',
	380: 'Italy',
	384: 'Ivory Coast',
	388: 'Jamaica',
	392: 'Japan',
	398: 'Kazakhstan',
	400: 'Jordan',
	404: 'Kenya',
	408: 'North Korea',
	410: 'South Korea',
	414: 'Kuwait',
	417: 'Kyrgyzstan',
	418: 'Laos',
	422: 'Lebanon',
	426: 'Lesotho',
	428: 'Latvia',
	430: 'Liberia',
	434: 'Libya',
	438: 'Liechtenstein',
	440: 'Lithuania',
	442: 'Luxembourg',
	446: 'Macau',
	450: 'Madagascar',
	454: 'Malawi',
	458: 'Malaysia',
	462: 'Maldives',
	466: 'Mali',
	470: 'Malta',
	474: 'Martinique',
	478: 'Mauritania',
	480: 'Mauritius',
	484: 'Mexico',
	492: 'Monaco',
	496: 'Mongolia',
	498: 'Moldova',
	499: 'Montenegro',
	500: 'Montserrat',
	504: 'Morocco',
	508: 'Mozambique',
	512: 'Oman',
	516: 'Namibia',
	520: 'Nauru',
	524: 'Nepal',
	528: 'Netherlands',
	531: 'Curaçao',
	533: 'Aruba',
	534: 'Sint Maarten',
	540: 'New Caledonia',
	548: 'Vanuatu',
	554: 'New Zealand',
	558: 'Nicaragua',
	562: 'Niger',
	566: 'Nigeria',
	570: 'Niue',
	574: 'Norfolk Island',
	578: 'Norway',
	580: 'Northern Mariana Islands',
	581: 'United States Minor Outlying Islands',
	583: 'Micronesia',
	584: 'Marshall Islands',
	585: 'Palau',
	586: 'Pakistan',
	591: 'Panama',
	598: 'Papua New Guinea',
	600: 'Paraguay',
	604: 'Peru',
	608: 'Philippines',
	612: 'Pitcairn Islands',
	616: 'Poland',
	620: 'Portugal',
	624: 'Guinea-Bissau',
	626: 'Timor-Leste',
	630: 'Puerto Rico',
	634: 'Qatar',
	638: 'Réunion',
	642: 'Romania',
	643: 'Russia',
	646: 'Rwanda',
	652: 'Saint Barthélemy',
	659: 'Saint Kitts and Nevis',
	660: 'Anguilla',
	662: 'Saint Lucia',
	663: 'Saint Martin',
	666: 'Saint Pierre and Miquelon',
	670: 'Saint Vincent and the Grenadines',
	674: 'San Marino',
	678: 'São Tomé and Príncipe',
	682: 'Saudi Arabia',
	686: 'Senegal',
	688: 'Serbia',
	690: 'Seychelles',
	694: 'Sierra Leone',
	702: 'Singapore',
	703: 'Slovakia',
	704: 'Vietnam',
	705: 'Slovenia',
	706: 'Somalia',
	710: 'South Africa',
	716: 'Zimbabwe',
	724: 'Spain',
	728: 'South Sudan',
	729: 'Sudan',
	732: 'Western Sahara',
	740: 'Suriname',
	744: 'Svalbard and Jan Mayen',
	748: 'Swaziland',
	752: 'Sweden',
	756: 'Switzerland',
	760: 'Syria',
	762: 'Tajikistan',
	764: 'Thailand',
	768: 'Togo',
	772: 'Tokelau',
	776: 'Tonga',
	780: 'Trinidad and Tobago',
	784: 'United Arab Emirates',
	788: 'Tunisia',
	792: 'Turkey',
	795: 'Turkmenistan',
	796: 'Turks and Caicos Islands',
	798: 'Tuvalu',
	800: 'Uganda',
	804: 'Ukraine',
	807: 'Macedonia',
	818: 'Egypt',
	826: 'United Kingdom',
	831: 'Guernsey',
	832: 'Jersey',
	833: 'Isle of Man',
	834: 'Tanzania',
	840: 'United States',
	850: 'United States Virgin Islands',
	854: 'Burkina Faso',
	858: 'Uruguay',
	860: 'Uzbekistan',
	862: 'Venezuela',
	876: 'Wallis and Futuna',
	882: 'Samoa',
	887: 'Yemen',
	894: 'Zambia',
	Aruba: 'Aruba',
	AW: 'Aruba',
	ABW: 'Aruba',
	ARU: 'Aruba',
	Afghanistan: 'Afghanistan',
	'Islamic Republic of Afghanistan': 'Afghanistan',
	AF: 'Afghanistan',
	'004': 'Afghanistan',
	AFG: 'Afghanistan',
	Angola: 'Angola',
	'Republic of Angola': 'Angola',
	AO: 'Angola',
	'024': 'Angola',
	AGO: 'Angola',
	ANG: 'Angola',
	Anguilla: 'Anguilla',
	AI: 'Anguilla',
	AIA: 'Anguilla',
	'Åland Islands': 'Åland Islands',
	AX: 'Åland Islands',
	ALA: 'Åland Islands',
	Albania: 'Albania',
	'Republic of Albania': 'Albania',
	AL: 'Albania',
	'008': 'Albania',
	ALB: 'Albania',
	Andorra: 'Andorra',
	'Principality of Andorra': 'Andorra',
	AD: 'Andorra',
	'020': 'Andorra',
	AND: 'Andorra',
	'United Arab Emirates': 'United Arab Emirates',
	AE: 'United Arab Emirates',
	ARE: 'United Arab Emirates',
	UAE: 'United Arab Emirates',
	Argentina: 'Argentina',
	'Argentine Republic': 'Argentina',
	AR: 'Argentina',
	'032': 'Argentina',
	ARG: 'Argentina',
	Armenia: 'Armenia',
	'Republic of Armenia': 'Armenia',
	AM: 'Armenia',
	'051': 'Armenia',
	ARM: 'Armenia',
	'American Samoa': 'American Samoa',
	AS: 'American Samoa',
	'016': 'American Samoa',
	ASM: 'American Samoa',
	ASA: 'American Samoa',
	Antarctica: 'Antarctica',
	AQ: 'Antarctica',
	'010': 'Antarctica',
	ATA: 'Antarctica',
	'French Southern and Antarctic Lands': 'French Southern and Antarctic Lands',
	'Territory of the French Southern and Antarctic Lands': 'French Southern and Antarctic Lands',
	TF: 'French Southern and Antarctic Lands',
	ATF: 'French Southern and Antarctic Lands',
	'Antigua and Barbuda': 'Antigua and Barbuda',
	AG: 'Antigua and Barbuda',
	'028': 'Antigua and Barbuda',
	ATG: 'Antigua and Barbuda',
	ANT: 'Antigua and Barbuda',
	Australia: 'Australia',
	'Commonwealth of Australia': 'Australia',
	AU: 'Australia',
	'036': 'Australia',
	AUS: 'Australia',
	Austria: 'Austria',
	'Republic of Austria': 'Austria',
	AT: 'Austria',
	'040': 'Austria',
	AUT: 'Austria',
	Azerbaijan: 'Azerbaijan',
	'Republic of Azerbaijan': 'Azerbaijan',
	AZ: 'Azerbaijan',
	'031': 'Azerbaijan',
	AZE: 'Azerbaijan',
	Burundi: 'Burundi',
	'Republic of Burundi': 'Burundi',
	BI: 'Burundi',
	BDI: 'Burundi',
	Belgium: 'Belgium',
	'Kingdom of Belgium': 'Belgium',
	BE: 'Belgium',
	'056': 'Belgium',
	BEL: 'Belgium',
	Benin: 'Benin',
	'Republic of Benin': 'Benin',
	BJ: 'Benin',
	BEN: 'Benin',
	'Burkina Faso': 'Burkina Faso',
	BF: 'Burkina Faso',
	BFA: 'Burkina Faso',
	BUR: 'Burkina Faso',
	Bangladesh: 'Bangladesh',
	"People's Republic of Bangladesh": 'Bangladesh',
	BD: 'Bangladesh',
	'050': 'Bangladesh',
	BGD: 'Bangladesh',
	BAN: 'Bangladesh',
	Bulgaria: 'Bulgaria',
	'Republic of Bulgaria': 'Bulgaria',
	BG: 'Bulgaria',
	BGR: 'Bulgaria',
	BUL: 'Bulgaria',
	Bahrain: 'Bahrain',
	'Kingdom of Bahrain': 'Bahrain',
	BH: 'Bahrain',
	'048': 'Bahrain',
	BHR: 'Bahrain',
	BRN: 'Brunei',
	Bahamas: 'Bahamas',
	'Commonwealth of the Bahamas': 'Bahamas',
	BS: 'Bahamas',
	'044': 'Bahamas',
	BHS: 'Bahamas',
	BAH: 'Bahamas',
	'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
	BA: 'Bosnia and Herzegovina',
	'070': 'Bosnia and Herzegovina',
	BIH: 'Bosnia and Herzegovina',
	'Saint Barthélemy': 'Saint Barthélemy',
	'Collectivity of Saint Barthélemy': 'Saint Barthélemy',
	BL: 'Saint Barthélemy',
	BLM: 'Saint Barthélemy',
	Belarus: 'Belarus',
	'Republic of Belarus': 'Belarus',
	BY: 'Belarus',
	BLR: 'Belarus',
	Belize: 'Belize',
	BZ: 'Belize',
	'084': 'Belize',
	BLZ: 'Belize',
	BIZ: 'Belize',
	Bermuda: 'Bermuda',
	BM: 'Bermuda',
	'060': 'Bermuda',
	BMU: 'Bermuda',
	BER: 'Bermuda',
	Bolivia: 'Bolivia',
	'Plurinational State of Bolivia': 'Bolivia',
	BO: 'Bolivia',
	'068': 'Bolivia',
	BOL: 'Bolivia',
	Brazil: 'Brazil',
	'Federative Republic of Brazil': 'Brazil',
	BR: 'Brazil',
	'076': 'Brazil',
	BRA: 'Brazil',
	Barbados: 'Barbados',
	BB: 'Barbados',
	'052': 'Barbados',
	BRB: 'Barbados',
	BAR: 'Barbados',
	Brunei: 'Brunei',
	'Nation of Brunei, Abode of Peace': 'Brunei',
	BN: 'Brunei',
	'096': 'Brunei',
	BRU: 'Brunei',
	Bhutan: 'Bhutan',
	'Kingdom of Bhutan': 'Bhutan',
	BT: 'Bhutan',
	'064': 'Bhutan',
	BTN: 'Bhutan',
	BHU: 'Bhutan',
	'Bouvet Island': 'Bouvet Island',
	BV: 'Bouvet Island',
	'074': 'Bouvet Island',
	BVT: 'Bouvet Island',
	Botswana: 'Botswana',
	'Republic of Botswana': 'Botswana',
	BW: 'Botswana',
	'072': 'Botswana',
	BWA: 'Botswana',
	BOT: 'Botswana',
	'Central African Republic': 'Central African Republic',
	CF: 'Central African Republic',
	CAF: 'Central African Republic',
	Canada: 'Canada',
	CA: 'Canada',
	CAN: 'Canada',
	'Cocos (Keeling) Islands': 'Cocos (Keeling) Islands',
	'Territory of the Cocos (Keeling) Islands': 'Cocos (Keeling) Islands',
	CC: 'Cocos (Keeling) Islands',
	CCK: 'Cocos (Keeling) Islands',
	Switzerland: 'Switzerland',
	'Swiss Confederation': 'Switzerland',
	CH: 'Switzerland',
	CHE: 'Switzerland',
	SUI: 'Switzerland',
	Chile: 'Chile',
	'Republic of Chile': 'Chile',
	CL: 'Chile',
	CHL: 'Chile',
	CHI: 'Chile',
	China: 'China',
	"People's Republic of China": 'China',
	CN: 'China',
	CHN: 'China',
	'Ivory Coast': 'Ivory Coast',
	"Republic of Côte d'Ivoire": 'Ivory Coast',
	CI: 'Ivory Coast',
	CIV: 'Ivory Coast',
	Cameroon: 'Cameroon',
	'Republic of Cameroon': 'Cameroon',
	CM: 'Cameroon',
	CMR: 'Cameroon',
	'DR Congo': 'DR Congo',
	'Democratic Republic of the Congo': 'DR Congo',
	CD: 'DR Congo',
	COD: 'DR Congo',
	'Republic of the Congo': 'Republic of the Congo',
	CG: 'Republic of the Congo',
	COG: 'Republic of the Congo',
	CGO: 'Republic of the Congo',
	'Cook Islands': 'Cook Islands',
	CK: 'Cook Islands',
	COK: 'Cook Islands',
	Colombia: 'Colombia',
	'Republic of Colombia': 'Colombia',
	CO: 'Colombia',
	COL: 'Colombia',
	Comoros: 'Comoros',
	'Union of the Comoros': 'Comoros',
	KM: 'Comoros',
	COM: 'Comoros',
	'Cape Verde': 'Cape Verde',
	'Republic of Cabo Verde': 'Cape Verde',
	CV: 'Cape Verde',
	CPV: 'Cape Verde',
	'Costa Rica': 'Costa Rica',
	'Republic of Costa Rica': 'Costa Rica',
	CR: 'Costa Rica',
	CRI: 'Costa Rica',
	CRC: 'Costa Rica',
	Cuba: 'Cuba',
	'Republic of Cuba': 'Cuba',
	CU: 'Cuba',
	CUB: 'Cuba',
	Curaçao: 'Curaçao',
	'Country of Curaçao': 'Curaçao',
	CW: 'Curaçao',
	CUW: 'Curaçao',
	'Christmas Island': 'Christmas Island',
	'Territory of Christmas Island': 'Christmas Island',
	CX: 'Christmas Island',
	CXR: 'Christmas Island',
	'Cayman Islands': 'Cayman Islands',
	KY: 'Cayman Islands',
	CYM: 'Cayman Islands',
	CAY: 'Cayman Islands',
	Cyprus: 'Cyprus',
	'Republic of Cyprus': 'Cyprus',
	CY: 'Cyprus',
	CYP: 'Cyprus',
	'Czech Republic': 'Czech Republic',
	CZ: 'Czech Republic',
	CZE: 'Czech Republic',
	Germany: 'Germany',
	'Federal Republic of Germany': 'Germany',
	DE: 'Germany',
	DEU: 'Germany',
	GER: 'Germany',
	Djibouti: 'Djibouti',
	'Republic of Djibouti': 'Djibouti',
	DJ: 'Djibouti',
	DJI: 'Djibouti',
	Dominica: 'Dominica',
	'Commonwealth of Dominica': 'Dominica',
	DM: 'Dominica',
	DMA: 'Dominica',
	Denmark: 'Denmark',
	'Kingdom of Denmark': 'Denmark',
	DK: 'Denmark',
	DNK: 'Denmark',
	DEN: 'Denmark',
	'Dominican Republic': 'Dominican Republic',
	DO: 'Dominican Republic',
	DOM: 'Dominican Republic',
	Algeria: 'Algeria',
	"People's Democratic Republic of Algeria": 'Algeria',
	DZ: 'Algeria',
	'012': 'Algeria',
	DZA: 'Algeria',
	ALG: 'Algeria',
	Ecuador: 'Ecuador',
	'Republic of Ecuador': 'Ecuador',
	EC: 'Ecuador',
	ECU: 'Ecuador',
	Egypt: 'Egypt',
	'Arab Republic of Egypt': 'Egypt',
	EG: 'Egypt',
	EGY: 'Egypt',
	Eritrea: 'Eritrea',
	'State of Eritrea': 'Eritrea',
	ER: 'Eritrea',
	ERI: 'Eritrea',
	'Western Sahara': 'Western Sahara',
	'Sahrawi Arab Democratic Republic': 'Western Sahara',
	EH: 'Western Sahara',
	ESH: 'Western Sahara',
	Spain: 'Spain',
	'Kingdom of Spain': 'Spain',
	ES: 'Spain',
	ESP: 'Spain',
	Estonia: 'Estonia',
	'Republic of Estonia': 'Estonia',
	EE: 'Estonia',
	EST: 'Estonia',
	Ethiopia: 'Ethiopia',
	'Federal Democratic Republic of Ethiopia': 'Ethiopia',
	ET: 'Ethiopia',
	ETH: 'Ethiopia',
	Finland: 'Finland',
	'Republic of Finland': 'Finland',
	FI: 'Finland',
	FIN: 'Finland',
	Fiji: 'Fiji',
	'Republic of Fiji': 'Fiji',
	FJ: 'Fiji',
	FJI: 'Fiji',
	FIJ: 'Fiji',
	'Falkland Islands': 'Falkland Islands',
	FK: 'Falkland Islands',
	FLK: 'Falkland Islands',
	France: 'France',
	'French Republic': 'France',
	FR: 'France',
	FRA: 'France',
	'Faroe Islands': 'Faroe Islands',
	FO: 'Faroe Islands',
	FRO: 'Faroe Islands',
	Micronesia: 'Micronesia',
	'Federated States of Micronesia': 'Micronesia',
	FM: 'Micronesia',
	FSM: 'Micronesia',
	Gabon: 'Gabon',
	'Gabonese Republic': 'Gabon',
	GA: 'Gabon',
	GAB: 'Gabon',
	'United Kingdom': 'United Kingdom',
	'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
	GB: 'United Kingdom',
	GBR: 'United Kingdom',
	Georgia: 'Georgia',
	GE: 'Georgia',
	GEO: 'Georgia',
	Guernsey: 'Guernsey',
	'Bailiwick of Guernsey': 'Guernsey',
	GG: 'Guernsey',
	GGY: 'Guernsey',
	Ghana: 'Ghana',
	'Republic of Ghana': 'Ghana',
	GH: 'Ghana',
	GHA: 'Ghana',
	Gibraltar: 'Gibraltar',
	GI: 'Gibraltar',
	GIB: 'Gibraltar',
	Guinea: 'Guinea',
	'Republic of Guinea': 'Guinea',
	GN: 'Guinea',
	GIN: 'Guinea',
	GUI: 'Guinea',
	Guadeloupe: 'Guadeloupe',
	GP: 'Guadeloupe',
	GLP: 'Guadeloupe',
	Gambia: 'Gambia',
	'Republic of the Gambia': 'Gambia',
	GM: 'Gambia',
	GMB: 'Gambia',
	GAM: 'Gambia',
	'Guinea-Bissau': 'Guinea-Bissau',
	'Republic of Guinea-Bissau': 'Guinea-Bissau',
	GW: 'Guinea-Bissau',
	GNB: 'Guinea-Bissau',
	GBS: 'Guinea-Bissau',
	'Equatorial Guinea': 'Equatorial Guinea',
	'Republic of Equatorial Guinea': 'Equatorial Guinea',
	GQ: 'Equatorial Guinea',
	GNQ: 'Equatorial Guinea',
	GEQ: 'Equatorial Guinea',
	Greece: 'Greece',
	'Hellenic Republic': 'Greece',
	GR: 'Greece',
	GRC: 'Greece',
	GRE: 'Greece',
	Grenada: 'Grenada',
	GD: 'Grenada',
	GRD: 'Grenada',
	GRN: 'Grenada',
	Greenland: 'Greenland',
	GL: 'Greenland',
	GRL: 'Greenland',
	Guatemala: 'Guatemala',
	'Republic of Guatemala': 'Guatemala',
	GT: 'Guatemala',
	GTM: 'Guatemala',
	GUA: 'Guatemala',
	'French Guiana': 'French Guiana',
	Guiana: 'French Guiana',
	GF: 'French Guiana',
	GUF: 'French Guiana',
	Guam: 'Guam',
	GU: 'Guam',
	GUM: 'Guam',
	Guyana: 'Guyana',
	'Co-operative Republic of Guyana': 'Guyana',
	GY: 'Guyana',
	GUY: 'Guyana',
	'Hong Kong': 'Hong Kong',
	"Hong Kong Special Administrative Region of the People's Republic of China": 'Hong Kong',
	HK: 'Hong Kong',
	HKG: 'Hong Kong',
	'Heard Island and McDonald Islands': 'Heard Island and McDonald Islands',
	HM: 'Heard Island and McDonald Islands',
	HMD: 'Heard Island and McDonald Islands',
	Honduras: 'Honduras',
	'Republic of Honduras': 'Honduras',
	HN: 'Honduras',
	HND: 'Honduras',
	HON: 'Honduras',
	Croatia: 'Croatia',
	'Republic of Croatia': 'Croatia',
	HR: 'Croatia',
	HRV: 'Croatia',
	CRO: 'Croatia',
	Haiti: 'Haiti',
	'Republic of Haiti': 'Haiti',
	HT: 'Haiti',
	HTI: 'Haiti',
	HAI: 'Haiti',
	Hungary: 'Hungary',
	HU: 'Hungary',
	HUN: 'Hungary',
	Indonesia: 'Indonesia',
	'Republic of Indonesia': 'Indonesia',
	ID: 'Indonesia',
	IDN: 'Indonesia',
	INA: 'Indonesia',
	'Isle of Man': 'Isle of Man',
	IM: 'Isle of Man',
	IMN: 'Isle of Man',
	India: 'India',
	'Republic of India': 'India',
	IN: 'India',
	IND: 'India',
	'British Indian Ocean Territory': 'British Indian Ocean Territory',
	IO: 'British Indian Ocean Territory',
	'086': 'British Indian Ocean Territory',
	IOT: 'British Indian Ocean Territory',
	Ireland: 'Ireland',
	'Republic of Ireland': 'Ireland',
	IE: 'Ireland',
	IRL: 'Ireland',
	Iran: 'Iran',
	'Islamic Republic of Iran': 'Iran',
	IR: 'Iran',
	IRN: 'Iran',
	IRI: 'Iran',
	Iraq: 'Iraq',
	'Republic of Iraq': 'Iraq',
	IQ: 'Iraq',
	IRQ: 'Iraq',
	Iceland: 'Iceland',
	IS: 'Iceland',
	ISL: 'Iceland',
	Israel: 'Israel',
	'State of Israel': 'Israel',
	IL: 'Israel',
	ISR: 'Israel',
	Italy: 'Italy',
	'Italian Republic': 'Italy',
	IT: 'Italy',
	ITA: 'Italy',
	Jamaica: 'Jamaica',
	JM: 'Jamaica',
	JAM: 'Jamaica',
	Jersey: 'Jersey',
	'Bailiwick of Jersey': 'Jersey',
	JE: 'Jersey',
	JEY: 'Jersey',
	Jordan: 'Jordan',
	'Hashemite Kingdom of Jordan': 'Jordan',
	JO: 'Jordan',
	JOR: 'Jordan',
	Japan: 'Japan',
	JP: 'Japan',
	JPN: 'Japan',
	Kazakhstan: 'Kazakhstan',
	'Republic of Kazakhstan': 'Kazakhstan',
	KZ: 'Kazakhstan',
	KAZ: 'Kazakhstan',
	Kenya: 'Kenya',
	'Republic of Kenya': 'Kenya',
	KE: 'Kenya',
	KEN: 'Kenya',
	Kyrgyzstan: 'Kyrgyzstan',
	'Kyrgyz Republic': 'Kyrgyzstan',
	KG: 'Kyrgyzstan',
	KGZ: 'Kyrgyzstan',
	Cambodia: 'Cambodia',
	'Kingdom of Cambodia': 'Cambodia',
	KH: 'Cambodia',
	KHM: 'Cambodia',
	CAM: 'Cambodia',
	Kiribati: 'Kiribati',
	'Independent and Sovereign Republic of Kiribati': 'Kiribati',
	KI: 'Kiribati',
	KIR: 'Kiribati',
	'Saint Kitts and Nevis': 'Saint Kitts and Nevis',
	'Federation of Saint Christopher and Nevisa': 'Saint Kitts and Nevis',
	KN: 'Saint Kitts and Nevis',
	KNA: 'Saint Kitts and Nevis',
	SKN: 'Saint Kitts and Nevis',
	'South Korea': 'South Korea',
	'Republic of Korea': 'South Korea',
	KR: 'South Korea',
	KOR: 'South Korea',
	Kosovo: 'Kosovo',
	'Republic of Kosovo': 'Kosovo',
	XK: 'Kosovo',
	UNK: 'Kosovo',
	KOS: 'Kosovo',
	Kuwait: 'Kuwait',
	'State of Kuwait': 'Kuwait',
	KW: 'Kuwait',
	KWT: 'Kuwait',
	KUW: 'Kuwait',
	Laos: 'Laos',
	"Lao People's Democratic Republic": 'Laos',
	LA: 'Laos',
	LAO: 'Laos',
	Lebanon: 'Lebanon',
	'Lebanese Republic': 'Lebanon',
	LB: 'Lebanon',
	LBN: 'Lebanon',
	LIB: 'Lebanon',
	Liberia: 'Liberia',
	'Republic of Liberia': 'Liberia',
	LR: 'Liberia',
	LBR: 'Liberia',
	Libya: 'Libya',
	'State of Libya': 'Libya',
	LY: 'Libya',
	LBY: 'Libya',
	LBA: 'Libya',
	'Saint Lucia': 'Saint Lucia',
	LC: 'Saint Lucia',
	LCA: 'Saint Lucia',
	Liechtenstein: 'Liechtenstein',
	'Principality of Liechtenstein': 'Liechtenstein',
	LI: 'Liechtenstein',
	LIE: 'Liechtenstein',
	'Sri Lanka': 'Sri Lanka',
	'Democratic Socialist Republic of Sri Lanka': 'Sri Lanka',
	LK: 'Sri Lanka',
	LKA: 'Sri Lanka',
	SRI: 'Sri Lanka',
	Lesotho: 'Lesotho',
	'Kingdom of Lesotho': 'Lesotho',
	LS: 'Lesotho',
	LSO: 'Lesotho',
	LES: 'Lesotho',
	Lithuania: 'Lithuania',
	'Republic of Lithuania': 'Lithuania',
	LT: 'Lithuania',
	LTU: 'Lithuania',
	Luxembourg: 'Luxembourg',
	'Grand Duchy of Luxembourg': 'Luxembourg',
	LU: 'Luxembourg',
	LUX: 'Luxembourg',
	Latvia: 'Latvia',
	'Republic of Latvia': 'Latvia',
	LV: 'Latvia',
	LVA: 'Latvia',
	LAT: 'Latvia',
	Macau: 'Macau',
	"Macao Special Administrative Region of the People's Republic of China": 'Macau',
	MO: 'Macau',
	MAC: 'Macau',
	'Saint Martin': 'Saint Martin',
	MF: 'Saint Martin',
	MAF: 'Saint Martin',
	Morocco: 'Morocco',
	'Kingdom of Morocco': 'Morocco',
	MA: 'Morocco',
	MAR: 'Morocco',
	Monaco: 'Monaco',
	'Principality of Monaco': 'Monaco',
	MC: 'Monaco',
	MCO: 'Monaco',
	MON: 'Monaco',
	Moldova: 'Moldova',
	'Republic of Moldova': 'Moldova',
	MD: 'Moldova',
	MDA: 'Moldova',
	Madagascar: 'Madagascar',
	'Republic of Madagascar': 'Madagascar',
	MG: 'Madagascar',
	MDG: 'Madagascar',
	MAD: 'Madagascar',
	Maldives: 'Maldives',
	'Republic of the Maldives': 'Maldives',
	MV: 'Maldives',
	MDV: 'Maldives',
	Mexico: 'Mexico',
	'United Mexican States': 'Mexico',
	MX: 'Mexico',
	MEX: 'Mexico',
	'Marshall Islands': 'Marshall Islands',
	'Republic of the Marshall Islands': 'Marshall Islands',
	MH: 'Marshall Islands',
	MHL: 'Marshall Islands',
	Macedonia: 'Macedonia',
	'Republic of Macedonia': 'Macedonia',
	MK: 'Macedonia',
	MKD: 'Macedonia',
	Mali: 'Mali',
	'Republic of Mali': 'Mali',
	ML: 'Mali',
	MLI: 'Mali',
	Malta: 'Malta',
	'Republic of Malta': 'Malta',
	MT: 'Malta',
	MLT: 'Malta',
	Myanmar: 'Myanmar',
	'Republic of the Union of Myanmar': 'Myanmar',
	MM: 'Myanmar',
	MMR: 'Myanmar',
	MYA: 'Myanmar',
	Montenegro: 'Montenegro',
	ME: 'Montenegro',
	MNE: 'Montenegro',
	Mongolia: 'Mongolia',
	MN: 'Mongolia',
	MNG: 'Mongolia',
	MGL: 'Mongolia',
	'Northern Mariana Islands': 'Northern Mariana Islands',
	'Commonwealth of the Northern Mariana Islands': 'Northern Mariana Islands',
	MP: 'Northern Mariana Islands',
	MNP: 'Northern Mariana Islands',
	Mozambique: 'Mozambique',
	'Republic of Mozambique': 'Mozambique',
	MZ: 'Mozambique',
	MOZ: 'Mozambique',
	Mauritania: 'Mauritania',
	'Islamic Republic of Mauritania': 'Mauritania',
	MR: 'Mauritania',
	MRT: 'Mauritania',
	MTN: 'Mauritania',
	Montserrat: 'Montserrat',
	MS: 'Montserrat',
	MSR: 'Montserrat',
	Martinique: 'Martinique',
	MQ: 'Martinique',
	MTQ: 'Martinique',
	Mauritius: 'Mauritius',
	'Republic of Mauritius': 'Mauritius',
	MU: 'Mauritius',
	MUS: 'Mauritius',
	MRI: 'Mauritius',
	Malawi: 'Malawi',
	'Republic of Malawi': 'Malawi',
	MW: 'Malawi',
	MWI: 'Malawi',
	MAW: 'Malawi',
	Malaysia: 'Malaysia',
	MY: 'Malaysia',
	MYS: 'Malaysia',
	MAS: 'Malaysia',
	Mayotte: 'Mayotte',
	'Department of Mayotte': 'Mayotte',
	YT: 'Mayotte',
	MYT: 'Mayotte',
	Namibia: 'Namibia',
	'Republic of Namibia': 'Namibia',
	NA: 'Namibia',
	NAM: 'Namibia',
	'New Caledonia': 'New Caledonia',
	NC: 'New Caledonia',
	NCL: 'New Caledonia',
	Niger: 'Niger',
	'Republic of Niger': 'Niger',
	NE: 'Niger',
	NER: 'Niger',
	NIG: 'Niger',
	'Norfolk Island': 'Norfolk Island',
	'Territory of Norfolk Island': 'Norfolk Island',
	NF: 'Norfolk Island',
	NFK: 'Norfolk Island',
	Nigeria: 'Nigeria',
	'Federal Republic of Nigeria': 'Nigeria',
	NG: 'Nigeria',
	NGA: 'Nigeria',
	NGR: 'Nigeria',
	Nicaragua: 'Nicaragua',
	'Republic of Nicaragua': 'Nicaragua',
	NI: 'Nicaragua',
	NIC: 'Nicaragua',
	NCA: 'Nicaragua',
	Niue: 'Niue',
	NU: 'Niue',
	NIU: 'Niue',
	Netherlands: 'Netherlands',
	NL: 'Netherlands',
	NLD: 'Netherlands',
	NED: 'Netherlands',
	Norway: 'Norway',
	'Kingdom of Norway': 'Norway',
	NO: 'Norway',
	NOR: 'Norway',
	Nepal: 'Nepal',
	'Federal Democratic Republic of Nepal': 'Nepal',
	NP: 'Nepal',
	NPL: 'Nepal',
	NEP: 'Nepal',
	Nauru: 'Nauru',
	'Republic of Nauru': 'Nauru',
	NR: 'Nauru',
	NRU: 'Nauru',
	'New Zealand': 'New Zealand',
	NZ: 'New Zealand',
	NZL: 'New Zealand',
	Oman: 'Oman',
	'Sultanate of Oman': 'Oman',
	OM: 'Oman',
	OMN: 'Oman',
	OMA: 'Oman',
	Pakistan: 'Pakistan',
	'Islamic Republic of Pakistan': 'Pakistan',
	PK: 'Pakistan',
	PAK: 'Pakistan',
	Panama: 'Panama',
	'Republic of Panama': 'Panama',
	PA: 'Panama',
	PAN: 'Panama',
	'Pitcairn Islands': 'Pitcairn Islands',
	'Pitcairn Group of Islands': 'Pitcairn Islands',
	PN: 'Pitcairn Islands',
	PCN: 'Pitcairn Islands',
	Peru: 'Peru',
	'Republic of Peru': 'Peru',
	PE: 'Peru',
	PER: 'Peru',
	Philippines: 'Philippines',
	'Republic of the Philippines': 'Philippines',
	PH: 'Philippines',
	PHL: 'Philippines',
	PHI: 'Philippines',
	Palau: 'Palau',
	'Republic of Palau': 'Palau',
	PW: 'Palau',
	PLW: 'Palau',
	'Papua New Guinea': 'Papua New Guinea',
	'Independent State of Papua New Guinea': 'Papua New Guinea',
	PG: 'Papua New Guinea',
	PNG: 'Papua New Guinea',
	Poland: 'Poland',
	'Republic of Poland': 'Poland',
	PL: 'Poland',
	POL: 'Poland',
	'Puerto Rico': 'Puerto Rico',
	'Commonwealth of Puerto Rico': 'Puerto Rico',
	PR: 'Puerto Rico',
	PRI: 'Puerto Rico',
	PUR: 'Puerto Rico',
	'North Korea': 'North Korea',
	"Democratic People's Republic of Korea": 'North Korea',
	KP: 'North Korea',
	PRK: 'North Korea',
	Portugal: 'Portugal',
	'Portuguese Republic': 'Portugal',
	PT: 'Portugal',
	PRT: 'Portugal',
	POR: 'Portugal',
	Paraguay: 'Paraguay',
	'Republic of Paraguay': 'Paraguay',
	PY: 'Paraguay',
	PRY: 'Paraguay',
	PAR: 'Paraguay',
	Palestine: 'Palestine',
	'State of Palestine': 'Palestine',
	PS: 'Palestine',
	PSE: 'Palestine',
	PLE: 'Palestine',
	'French Polynesia': 'French Polynesia',
	PF: 'French Polynesia',
	PYF: 'French Polynesia',
	Qatar: 'Qatar',
	'State of Qatar': 'Qatar',
	QA: 'Qatar',
	QAT: 'Qatar',
	Réunion: 'Réunion',
	'Réunion Island': 'Réunion',
	RE: 'Réunion',
	REU: 'Réunion',
	Romania: 'Romania',
	RO: 'Romania',
	ROU: 'Romania',
	Russia: 'Russia',
	'Russian Federation': 'Russia',
	RU: 'Russia',
	RUS: 'Russia',
	Rwanda: 'Rwanda',
	'Republic of Rwanda': 'Rwanda',
	RW: 'Rwanda',
	RWA: 'Rwanda',
	'Saudi Arabia': 'Saudi Arabia',
	'Kingdom of Saudi Arabia': 'Saudi Arabia',
	SA: 'Saudi Arabia',
	SAU: 'Saudi Arabia',
	KSA: 'Saudi Arabia',
	Sudan: 'Sudan',
	'Republic of the Sudan': 'Sudan',
	SD: 'Sudan',
	SDN: 'Sudan',
	SUD: 'Sudan',
	Senegal: 'Senegal',
	'Republic of Senegal': 'Senegal',
	SN: 'Senegal',
	SEN: 'Senegal',
	Singapore: 'Singapore',
	'Republic of Singapore': 'Singapore',
	SG: 'Singapore',
	SGP: 'Singapore',
	SIN: 'Singapore',
	'South Georgia': 'South Georgia',
	'South Georgia and the South Sandwich Islands': 'South Georgia',
	GS: 'South Georgia',
	SGS: 'South Georgia',
	'Svalbard and Jan Mayen': 'Svalbard and Jan Mayen',
	'Svalbard og Jan Mayen': 'Svalbard and Jan Mayen',
	SJ: 'Svalbard and Jan Mayen',
	SJM: 'Svalbard and Jan Mayen',
	'Solomon Islands': 'Solomon Islands',
	SB: 'Solomon Islands',
	'090': 'Solomon Islands',
	SLB: 'Solomon Islands',
	SOL: 'Solomon Islands',
	'Sierra Leone': 'Sierra Leone',
	'Republic of Sierra Leone': 'Sierra Leone',
	SL: 'Sierra Leone',
	SLE: 'Sierra Leone',
	'El Salvador': 'El Salvador',
	'Republic of El Salvador': 'El Salvador',
	SV: 'El Salvador',
	SLV: 'El Salvador',
	ESA: 'El Salvador',
	'San Marino': 'San Marino',
	'Most Serene Republic of San Marino': 'San Marino',
	SM: 'San Marino',
	SMR: 'San Marino',
	Somalia: 'Somalia',
	'Federal Republic of Somalia': 'Somalia',
	SO: 'Somalia',
	SOM: 'Somalia',
	'Saint Pierre and Miquelon': 'Saint Pierre and Miquelon',
	PM: 'Saint Pierre and Miquelon',
	SPM: 'Saint Pierre and Miquelon',
	Serbia: 'Serbia',
	'Republic of Serbia': 'Serbia',
	RS: 'Serbia',
	SRB: 'Serbia',
	'South Sudan': 'South Sudan',
	'Republic of South Sudan': 'South Sudan',
	SS: 'South Sudan',
	SSD: 'South Sudan',
	'São Tomé and Príncipe': 'São Tomé and Príncipe',
	'Democratic Republic of São Tomé and Príncipe': 'São Tomé and Príncipe',
	ST: 'São Tomé and Príncipe',
	STP: 'São Tomé and Príncipe',
	Suriname: 'Suriname',
	'Republic of Suriname': 'Suriname',
	SR: 'Suriname',
	SUR: 'Suriname',
	Slovakia: 'Slovakia',
	'Slovak Republic': 'Slovakia',
	SK: 'Slovakia',
	SVK: 'Slovakia',
	Slovenia: 'Slovenia',
	'Republic of Slovenia': 'Slovenia',
	SI: 'Slovenia',
	SVN: 'Slovenia',
	SLO: 'Slovenia',
	Sweden: 'Sweden',
	'Kingdom of Sweden': 'Sweden',
	SE: 'Sweden',
	SWE: 'Sweden',
	Swaziland: 'Swaziland',
	'Kingdom of Swaziland': 'Swaziland',
	SZ: 'Swaziland',
	SWZ: 'Swaziland',
	'Sint Maarten': 'Sint Maarten',
	SX: 'Sint Maarten',
	SXM: 'Sint Maarten',
	Seychelles: 'Seychelles',
	'Republic of Seychelles': 'Seychelles',
	SC: 'Seychelles',
	SYC: 'Seychelles',
	SEY: 'Seychelles',
	Syria: 'Syria',
	'Syrian Arab Republic': 'Syria',
	SY: 'Syria',
	SYR: 'Syria',
	'Turks and Caicos Islands': 'Turks and Caicos Islands',
	TC: 'Turks and Caicos Islands',
	TCA: 'Turks and Caicos Islands',
	Chad: 'Chad',
	'Republic of Chad': 'Chad',
	TD: 'Chad',
	TCD: 'Chad',
	CHA: 'Chad',
	Togo: 'Togo',
	'Togolese Republic': 'Togo',
	TG: 'Togo',
	TGO: 'Togo',
	TOG: 'Togo',
	Thailand: 'Thailand',
	'Kingdom of Thailand': 'Thailand',
	TH: 'Thailand',
	THA: 'Thailand',
	Tajikistan: 'Tajikistan',
	'Republic of Tajikistan': 'Tajikistan',
	TJ: 'Tajikistan',
	TJK: 'Tajikistan',
	Tokelau: 'Tokelau',
	TK: 'Tokelau',
	TKL: 'Tokelau',
	Turkmenistan: 'Turkmenistan',
	TM: 'Turkmenistan',
	TKM: 'Turkmenistan',
	'Timor-Leste': 'Timor-Leste',
	'Democratic Republic of Timor-Leste': 'Timor-Leste',
	TL: 'Timor-Leste',
	TLS: 'Timor-Leste',
	Tonga: 'Tonga',
	'Kingdom of Tonga': 'Tonga',
	TO: 'Tonga',
	TON: 'Tonga',
	TGA: 'Tonga',
	'Trinidad and Tobago': 'Trinidad and Tobago',
	'Republic of Trinidad and Tobago': 'Trinidad and Tobago',
	TT: 'Trinidad and Tobago',
	TTO: 'Trinidad and Tobago',
	Tunisia: 'Tunisia',
	'Tunisian Republic': 'Tunisia',
	TN: 'Tunisia',
	TUN: 'Tunisia',
	Turkey: 'Turkey',
	'Republic of Turkey': 'Turkey',
	TR: 'Turkey',
	TUR: 'Turkey',
	Tuvalu: 'Tuvalu',
	TV: 'Tuvalu',
	TUV: 'Tuvalu',
	Taiwan: 'Taiwan',
	'Republic of China (Taiwan)': 'Taiwan',
	TW: 'Taiwan',
	TWN: 'Taiwan',
	TPE: 'Taiwan',
	Tanzania: 'Tanzania',
	'United Republic of Tanzania': 'Tanzania',
	TZ: 'Tanzania',
	TZA: 'Tanzania',
	TAN: 'Tanzania',
	Uganda: 'Uganda',
	'Republic of Uganda': 'Uganda',
	UG: 'Uganda',
	UGA: 'Uganda',
	Ukraine: 'Ukraine',
	UA: 'Ukraine',
	UKR: 'Ukraine',
	'United States Minor Outlying Islands': 'United States Minor Outlying Islands',
	UM: 'United States Minor Outlying Islands',
	UMI: 'United States Minor Outlying Islands',
	Uruguay: 'Uruguay',
	'Oriental Republic of Uruguay': 'Uruguay',
	UY: 'Uruguay',
	URY: 'Uruguay',
	URU: 'Uruguay',
	'United States': 'United States',
	'United States of America': 'United States',
	US: 'United States',
	USA: 'United States',
	Uzbekistan: 'Uzbekistan',
	'Republic of Uzbekistan': 'Uzbekistan',
	UZ: 'Uzbekistan',
	UZB: 'Uzbekistan',
	'Vatican City': 'Vatican City',
	'Vatican City State': 'Vatican City',
	VA: 'Vatican City',
	VAT: 'Vatican City',
	'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
	VC: 'Saint Vincent and the Grenadines',
	VCT: 'Saint Vincent and the Grenadines',
	VIN: 'Saint Vincent and the Grenadines',
	Venezuela: 'Venezuela',
	'Bolivarian Republic of Venezuela': 'Venezuela',
	VE: 'Venezuela',
	VEN: 'Venezuela',
	'British Virgin Islands': 'British Virgin Islands',
	'Virgin Islands': 'British Virgin Islands',
	VG: 'British Virgin Islands',
	'092': 'British Virgin Islands',
	VGB: 'British Virgin Islands',
	IVB: 'British Virgin Islands',
	'United States Virgin Islands': 'United States Virgin Islands',
	'Virgin Islands of the United States': 'United States Virgin Islands',
	VI: 'United States Virgin Islands',
	VIR: 'United States Virgin Islands',
	ISV: 'United States Virgin Islands',
	Vietnam: 'Vietnam',
	'Socialist Republic of Vietnam': 'Vietnam',
	VN: 'Vietnam',
	VNM: 'Vietnam',
	VIE: 'Vietnam',
	Vanuatu: 'Vanuatu',
	'Republic of Vanuatu': 'Vanuatu',
	VU: 'Vanuatu',
	VUT: 'Vanuatu',
	VAN: 'Vanuatu',
	'Wallis and Futuna': 'Wallis and Futuna',
	'Territory of the Wallis and Futuna Islands': 'Wallis and Futuna',
	WF: 'Wallis and Futuna',
	WLF: 'Wallis and Futuna',
	Samoa: 'Samoa',
	'Independent State of Samoa': 'Samoa',
	WS: 'Samoa',
	WSM: 'Samoa',
	SAM: 'Samoa',
	Yemen: 'Yemen',
	'Republic of Yemen': 'Yemen',
	YE: 'Yemen',
	YEM: 'Yemen',
	'South Africa': 'South Africa',
	'Republic of South Africa': 'South Africa',
	ZA: 'South Africa',
	ZAF: 'South Africa',
	RSA: 'South Africa',
	Zambia: 'Zambia',
	'Republic of Zambia': 'Zambia',
	ZM: 'Zambia',
	ZMB: 'Zambia',
	ZAM: 'Zambia',
	Zimbabwe: 'Zimbabwe',
	'Republic of Zimbabwe': 'Zimbabwe',
	ZW: 'Zimbabwe',
	ZWE: 'Zimbabwe',
	ZIM: 'Zimbabwe',
};
